### ISSUE TITLE
How to determine if no window/item has focus?

### ISSUE THREAD

**Issue by ands** [vurtun/nuklear#107]
I'm searching for a way to get the behaviour of ImGui::IsAnyItemActive() from dear imgui.
This function told me whether any item has focus or not.
If no item has focus, I want my own code to handle mouse/keyboard input.

I've tried using nk_window_is_any_hovered, but it would return false when using a slider or property and moving the mouse out of the window during an interaction.

I've tried using nk_window_is_active / ctx->active, but these are always set for/to some window.

Is there a way to get that behaviour?

**Comment by vurtun** [comment]
At least not out of the box. I do not store anything about the currently active widget directly (would require some kind of ID for every widget). Nonetheless there could be a way to achieve the same result by using `last_widget_state` inside the `nk_context`. I will test it out and see what I can do. But at the moment I am not quite sure that it even works for slider or properties as well (exactly because I don't store the active widget).

**Comment by fr500** [comment]
Don't you think keeping a track of the active widget would be useful? remember the gamepad friendly widgets you made before? it would be useful to for tab/shift-tab based navigation too.

**Comment by dumblob** [comment]
@fr500 it would be definitely useful, but it would complicate things especially because of the need to support [more simultaneous inputs](https://github.com/vurtun/nuklear/issues/26) and thus somehow deciding whether to store information about more than one active widgets or just one (and in this case which one - the first pressed? or any other?).

**Comment by vurtun** [comment]
Sadly this has nothing to do with me not wanting it. But with tradeoffs. Either a.) I make this library hard to use for everyone by requiring an unique ID for every widget that will be unique even after changes to the UI or b.) make it a harder for those who want to use it with gamepad/keyboard which already requires different widgets (see gamepad demo). The good thing for the gamepad demo I made was that the UI was static in the sense that nothing was added or removed while running. In these cases it is enough to just have a growing ID. Nuklear's API is not magic even though I try my best to make it so that as many things implicitly just work. But some things have to come from somewhere and I try to make the general case easier.
