### ISSUE TITLE
Implement mouse grabber?

### ISSUE THREAD

**Issue by starwing** [vurtun/nuklear#116]
Hi, vurtun, Thanks for your GREAT project! it's a dream thing that I always wanted, A pure C portable UI framework.

After build examples and demos on Windows, I notice that the widgets in nuklear do not follow mouse grabber.

In [Windows][1] or other tookit, when you press down a mouse button, a widget should accept this event. After that, the widget become a "mouse grabber", means that if you hold down and move your mouse, only that widget can receive mouse event. if you move mouse to close button, and release, the close button (not the grabber) will not trigger. the grabber widget triggered only the mouse release and the pointer is in this widget.

Is this a normal design? I don't know how it is in imgui or other embedded toolkits. so we can discuss about whether it's important or not.

regards :)

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646262(v=vs.85).aspx

**Comment by lieff** [comment]
+1, sliders almost not usable without it.

**Comment by vurtun** [comment]
@starwing:
> After build examples and demos on Windows, I notice that the widgets in nuklear do not follow mouse grabber.

Properties and Scrollbars are at the moment the only widgets who do. 

> In Windows or other tookit, when you press down a mouse button, a widget should accept this event. After that, the widget become a "mouse grabber", means that if you hold down and move your mouse, only that widget can receive mouse event. if you move mouse to close button, and release, the close button (not the grabber) will not trigger. the grabber widget triggered only the mouse release and the pointer is in this widget.

All clickable interaction widgets work on mouse button up instead of button down. The reason are touch interfaces (you can find more about that discussion here #39). But now that I got two different complains in either direction I probably will add a compiling flag to let the user decide which behavior should be used. It shouldn't be to hard to do.

@lieff 
> sliders almost not usable without it.

I should be able to modify sliding behavior to act the same as properties. You click on it and you can modify it even if you are not directly hovering over it. Same as above shouldn't be to hard and I will fix it.

**Comment by starwing** [comment]
@vurtun thanks for fix! but the progress should follow grabber, too.

and I notice that the silder is not real capture the mouse. I mean, if I drag the silder, it moves, and if I outside the sider, it still moves, but other widgets still get mouse event. e.g. I move mouse to the title of panel, and the panel moves, this makes sider not such useful even in touch screens. a proper mouse grabber handling should prevent other widget receive mouse event when mouse grabbered.

and I doubt  touch screen handle button press, because my Android phone handle button release. this give me a chance to cancel my choice even I pressed the button, and support long press. and if I leave my finger quickly, the button works well as handle press.

**Comment by vurtun** [comment]
> thanks for fix! but the progress should follow grabber, too.

Yeah I still need to fix some other draggable widgets, it is not really complicated I just forgot abut them. 

> I notice that the silder is not real capture the mouse

That is correct as well. The reason is simply that immediate mode GUIs are not like classic retain mode GUIs and especially this implementation does not store any widget dependent state (not quite correct eg.: edit, property) so what you call mouse capture is not possible and only emulated on the library side. 

>  I doubt touch screen handle button press, because my Android phone handle button release. this give me a chance to cancel my choice even I pressed the button, and support long press. and if I leave my finger quickly, the button works well as handle press.

I said **nothing** to the opposite. What I do say now is that for PC a button pressed implementation is preferable while on touch device a button release approach is better. **That** is the reason why I added another compiler flag `NK_BUTTON_TRIGGER_ON_RELEASE` to let the user of this library decide which one he/she wants!

**Comment by starwing** [comment]
Sorry for misunderstanding, I don't mean any implement is bad, just give some my personal opinion.

I now understand about library, and it's okay in that reason. it is still a great library! thanks for your work.

build gdi example seems broken, I added `time.h` include and `LEN`, `MAX` macro to overview.c and now it works.
