### ISSUE TITLE
Ship backends as separate headers

### ISSUE THREAD

**Issue by jimon** [vurtun/nuklear#118]
Just an idea! Maybe it's feasible to ship backends in a similar fashion (like one header lib), so in case if nuklear change rendering or input api we have a little bit more control over how the lib interfaces with  backends.

Basically what I'm proposing is instead of having every flavor in demo/* maybe it's better to make nuklear_glfw.h or something, that just provide predefined way to use nuklear with specific backend. Also this should make bootstrapping a new app much more easier :) On another hand it's essential to preserve rendering\input api so people can create their own implementations.

**Comment by dumblob** [comment]
Well, the idea itself seems nice. But I think it's not feasible because of maintainability. I would just leave backends fully up to the decision of an end-user and really provide only the "flavoured" demos without any "responsibility" for using them in production code.

But of course, if more stable developers of Zahnrad appear, we can embrace also these "standard backends".

**Comment by vurtun** [comment]
@jimon 
> Basically what I'm proposing is instead of having every flavor in demo/* maybe it's better to make nuklear_glfw.h or something,

Correct me if I am wrong but what I read out of it is basically you want all backends to be on the same level of quality like the main library so everyone can just paste it in an use it as a single header library. So far at least at the moment this is the way I am heading in development (I just make a lot of small changes at a time). I am still trying to figure out how all demos should be structured and work. For example all current demos do not work with multiple windows and contexts. I am also trying to get rid of GLEW which I don't really want or need as a dependency. This is the main reason why I would choose single header demos. So it is easier to modify behavior like for example to turn OpenGL extension loading on and off.

@dumblob    
> But I think it's not feasible because of maintainability. I would just leave backends fully up to the decision of an end-user and really provide only the "flavoured" demos without any "responsibility" for using them in production code.

I would agree to your point in instances were users want to control everything this library provides like total memory control, font handling control, .etc. In these cases writing you own backend is basically the only real option at least at the moment, I will try to fix that if possible. The reality however is everyone who encounters this library wants to do the least amount of work to get something running. Most of the time it comes down to copy & pasting the demo code without doing any changes. So it is important to have good quality example backend and demo code since most of the time it is the entry point to this library. Especially since users do not want to read documentation or read the library itself to figure out what needs to be done.

**Comment by jimon** [comment]
@vurtun 

> you want all backends to be on the same level of quality like the main library

Yes, but I don't think quality is the key point here - it will be an utopia to actually support all backends with all kind of customizations customers want (and do CI on all of them). Maybe just support the rendering and input, and leave program entry point to customers to deal with. So it's like 

> so everyone can just paste it in an use it as a single header library

Yes, though I don't have a strong feeling if backends needs to be in the main library header or shipped as separate headers.

**Comment by vurtun** [comment]
>  Maybe just support the rendering and input, and leave program entry point to customers to deal with.

Isn't that exactly what I am doing right now?

> Yes, though I don't have a strong feeling if backends needs to be in the main library header or shipped as separate headers.

I already converted all demos into single header libraries (I will not put any platform depended code inside the library).

**Comment by jimon** [comment]
> I already converted all demos into single header libraries (I will not put any platform depended code inside the library).

Oh, sorry, missed that! Maybe just put them to root folder (or backend-something-ish) to make it more obvious? Then I guess we can close this one as done :+1:

**Comment by vurtun** [comment]
I had them in the root directory on my system but it decided to put it back into each demo directory. It is easier to comprehend the library if you first just see the the core library file and then choose what you want by selecting the demo backend you want to use instead of being bombarded by `12+` backend files.
