### ISSUE TITLE
Menubar content clipping issue

### ISSUE THREAD

**Issue by sammyfreg** [vurtun/nuklear#119]
I recently discovered ImGui and integrated it to my home engine to good results. I then discovered Nuklear last week and decided to give it a go, since the layout seems more flexible and there's more rendering options available. Thanks for the great work! It's really helpfull for us hobbyist wanting minimalist debug UI functionalities without all kind of complicated dependencies. :+1: 

While trying to replicate ImGui 'MainMenuBar' functionality, I encountered a few issues. In ImGui, this feature allows you to : 
- Display a simple menu bar at the top of the 'Display zone', not tied to a particular window (think MacOS top menu bar)
- Have multiple entry points adding menu option (example : _Engine adds a 'Engine' entry with various options, while the 'Game' adds it own menu entry, later in the update loop)_

Now, I have mostly achieved the same results in Nuklear, but using a fews hacks making it it less coder friendly.
- There's no 'MainMenuBar' so I created a thin window on the top of the display area, setting all padding, spacing, etc.. to 0.
- I didn't see how I could append entries to this menu (from various code location) after having created the menubar, with each item appearing side by side. This might be possible to achieve and I'm just not familiar enough witth the layout system.

**Real issue**
Since I only want a Menubar, I set the window height to thin (20), causing issue with the popup associated with menu items. The popup gets clipped to the window height, so we never see it. To get around this, I manually change the window height post creation / pre menu item, but this feels too hackish : `Context.current->layout->bounds.h = 400`

Would it be possible to consider not clipping menu popup to window height, or offering flags to not clip  ?
As an aside, ImGui has a function called _ImGui::ShowTestWindow()_ that's really usefull to graps quickly all the functionalities availabe and how to use them, very useful when doc is limited. I have seen the samples, but compiling them is more complex (rendering dependencies) than just having it straight in the engine you are integrating Nuklear to, and do not seems to explain the layout details.

Good work and thanks again for this nice library.

**Comment by vurtun** [comment]
Disclaimer: I read what I just wrote and it sound a lot more ranty and grumpy than wanted. I am feeling under the weather and have a headache so please don't put to much into my words here.

> I didn't see how I could append entries to this menu (from various code location) after having created the menubar, with each item appearing side by side. This might be possible to achieve and I'm just not familiar enough witth the layout system.

It is not possible to have nested menu entries. There are two different reasons for that.
a.) Technical: Since Nuklear is a lot more simple it does not support popup inside of popups
b.) Design: There is no reason to even use nested menus in immediate mode UIs.

The first reason resulted from my decision to keep memory handling extremely simple. So it is possible to just provide one memory block for everything. This resulted into me only having one buffer to queue draw commands into instead of one per window/popup like imgui. I don't want to go to far down into implementation details but because of that decision it is not possible to have nested popups (I would have to rewrite the whole library to change it and I would loose a lot of simplicity).

The second reason is probably a little bit more controversial. At least for me the main reason nested menu popup even exist is because of the design of old school GUI libraries. For them it is quite complicated to change the UI so it is easier to create something new than to modify existing space. With immediate mode GUIs this is not true anymore. You can change everything inside the menu popup. Combined with the power of imgui's to fill panels with whatever content and there is no reason in my opinion to have a shitty concept like nested menus to even exist. For example I wrote a small example in ~5 minutes to quickly demonstrate that you can fill menu with everything you could fill the normal window with:

```c
nk_menubar_begin(ctx);
if (nk_menu_begin_label(ctx, &menu, "ADVANCED", NK_TEXT_LEFT, 200))
{
    if (nk_tree_push(ctx, NK_TREE_TAB, "EDIT", NK_MINIMIZED)) {
        nk_menu_item_label(ctx, "Copy", NK_TEXT_LEFT);
        nk_menu_item_label(ctx, "Delete", NK_TEXT_LEFT);
        nk_menu_item_label(ctx, "Cut", NK_TEXT_LEFT);
        nk_menu_item_label(ctx, "Paste", NK_TEXT_LEFT);
        nk_tree_pop(ctx);
    }
    if (nk_tree_push(ctx, NK_TREE_TAB, "VIEW", NK_MINIMIZED)) {
        nk_menu_item_label(ctx, "About", NK_TEXT_LEFT);
        nk_menu_item_label(ctx, "Options", NK_TEXT_LEFT);
        nk_menu_item_label(ctx, "Customize", NK_TEXT_LEFT);
        nk_tree_pop(ctx);
    }
    if (nk_tree_push(ctx, NK_TREE_TAB, "CHART", NK_MINIMIZED)) {
        size_t i = 0;
        const float values[]={26.0f,13.0f,30.0f,15.0f,25.0f,10.0f,20.0f,40.0f,12.0f,8.0f,22.0f,28.0f};
        nk_layout_row_dynamic(ctx, 150, 1);
        nk_chart_begin(ctx, NK_CHART_COLUMN, LEN(values), 0, 50);
        for (i = 0; i < LEN(values); ++i) nk_chart_push(ctx, values[i]);
        nk_chart_end(ctx);
        nk_tree_pop(ctx);
    }
    nk_menu_end(ctx);
}
nk_menubar_end(ctx);
```
![menu](https://cloud.githubusercontent.com/assets/8057201/14955600/615f34d8-107b-11e6-871f-3042fee123bb.png)

You could also fill menus with `groups`,  `trees` and all the other complex layouts found inside windows. So there is at least in my opinion no benefit of copying what retain mode UIs previously could do with nested menus and instead I would recommend trying out new ways and embrace what immediate mode GUIs provide.

> Since I only want a Menubar, I set the window height to thin (20), causing issue with the popup associated with menu items. The popup gets clipped to the window height, so we never see it. To get around this, I manually change the window height post creation / pre menu item, but this feels too hackish : Context.current->layout->bounds.h = 400

This is a bug and I will push a fix ASAP. Only requires changing one line of code. I would also recommend setting following style properties to zero if not done already:

```c
ctx->style.window.spacing = nk_vec2(0,0);
ctx->style.window.scaler_size = nk_vec2(0,0);
ctx->style.window.footer_padding = nk_vec2(0,0);
ctx->style.window.padding = nk_vec2(0,0);
ctx->style.window.header.label_padding = nk_vec2(0,0);
ctx->style.window.header.padding = nk_vec2(0,0);
```
> As an aside, ImGui has a function called ImGui::ShowTestWindow() that's really usefull to graps quickly all the functionalities availabe and how to use them, very useful when doc is limited. I have seen the samples, but compiling them is more complex (rendering dependencies) than just having it straight in the engine you are integrating Nuklear to, and do not seems to explain the layout details.

You can literally copy and paste the window function `overview()` in `overview.c` and stick it into your project and it will just run and you can use it as a reference point. This was the main reason why I put them into different files, to make sure they are easy to copy and paste into your own project. So I will not put any demo code inside the main library.

**Comment by dumblob** [comment]
Except for leveraging simplicity and embracing new concepts, it's certainly possible to reimplement "nested" menus outside of Nuklear, because there is only one requirement for menus - to be on top of the surface.

This functionality is though already provided by Nuklear, so why not to draw a huge rectangle fully transparent and into it draw your own items in columns while making some of them transparent to mimic nested menus? I didn't try it, but it's the way I would try to explore first if I wanted to implement nested menus using Nuklear.

**Comment by sammyfreg** [comment]
Hi, I think I didn't express myself properly when talking about the menu, I wasn't talking about submenu in menus (didn't get that far yet).

**Here's simple example to illustrate my point** :
- _(In EngineUI at the end of the frame)_
- Create menu bar Window
- Add entry 'Engine' and 'System' (now have # Engine System # at the top)
- Done with menu
- Create a new profiling window, displaying some fps stats
- _(Now in GameUI)_
- Create same menubar and try to append entry 'Game' to it (to have # Engine System Game #)

At the moment, I end up overwriting the Menubar instead of appending 'Game'.

If this is not currently possible, I will implement a callback system to request the MainMenu entries wanted and draw it all from within the window creation code.

**Comment by vurtun** [comment]
Ah OK then I completely misunderstood. In theory it would be possible but it would require two different `nk_context`. With context A you start `EngineUI` and create the menubar and two items #Engine and #System. Then you go over the context B and create the GameUI window.  After that you get back to context B and add item #Game to the menubar and finally draw context A and then context B. At least if I understand your problem correctly.
Problem of this approach are wasted memory, complexity and forces one of the the window always into the background. So while possible I don't know if I can really recommend doing it.
