### ISSUE TITLE
can you provide an example that work for rpi ?

### ISSUE THREAD

**Issue by malv-c** [vurtun/nuklear#121]
i did look in the makefile of example and it link gl glfw ...
mesa and all in armv7l distros does not work on gpu of rpi
on arm the vendor libegl libglesv2 does work on gpu
in rpi we have libopenvg libopenmaxil too
so is it possible to work with this ?

**Comment by vurtun** [comment]
What exactly do you need? As far as I know it shouldn't be to much work converting OpenGL version 3.X to OpenGL ES 2.0. As far as I know there is only a small number of differences between both versions, at least for the required subset for this library. So I would recommend starting with one of the OpenGL 3.X demos and exchange all functions not supported by OpenGL ES 2.0.

**Comment by malv-c** [comment]
i expcted a working example to not have to learn opengl* and start a direct gui for rpi ;)

**Comment by vurtun** [comment]
First off there is nothing to "expect", besides what already exists inside this library that I spend 1 1/2 years on. I am not your employee, I don't get money for this library and I donated a lot my time to write it in the first place. I will do what I can to fix all bugs and in general try to make everything as easy as possible for users. But I will not write a backend for every existing platform and user or even accept a PR for platforms I cannot test on, because I will be the one in the end maintaining all of them which is a shit ton of work for 12+ backends already. Especially in this case were most of the work is already done and only already existing code most be modified.

**Comment by malv-c** [comment]
so you have no openglesv2 board to test (interesting : why ?)
arm boards are far less expensive than x86* ones and are enough powerful for normal use
