### ISSUE TITLE
Performance comparison with imgui?

### ISSUE THREAD

**Issue by VinnyVicious** [vurtun/nuklear#134]
How fast is nuklear compared to imgui? Are they too different?

**Comment by vurtun** [comment]
Neither Omar nor I did any tests to find out, since both of us don't really care very much. That being said I think dear imgui should be faster than Nuklear since while performance was important it was not as high a priority for me as for @ocornut (at least as far as I know). So to answer your question dear imgui is probably faster but I don't think it will make to much of a difference.
