### ISSUE TITLE
Render a lot of widget bug in glfw gl2,can't display properly

### ISSUE THREAD

**Issue by linuxempire** [vurtun/nuklear#149]
code:
	struct nk_panel layout;
	if (nk_begin(ctx, &layout, "Main", nk_rect(50, 50, 1200, 900),
		NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|
		NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE))
	{
		int i;
		int b = 0;
		int selected[10000];
		for (i = 0; i < 10000; i++) {
			selected[i] = b; b ^= 1;
		}
		nk_layout_row_static(ctx, 5, 5, 120);
		for (i = 0; i < 10000; ++i) {
			if (nk_selectable_label(ctx, "Z", NK_TEXT_CENTERED, &selected[i])) {
			}
		}
	}
	nk_end(ctx);

**Comment by vurtun** [comment]
Hm I tried it out and it seems to work correctly for me. What exactly is your problem, maybe I am overlooking something?: 
![bug](https://cloud.githubusercontent.com/assets/8057201/15453900/498fbc22-2027-11e6-853c-c9cc424a4f32.png)

If you mean why it does not draw the correct selection background that is quite simple. The font is 13 pixel high and each of your `nk_selectable_label` has a size of 5x5 and is therefore to small. I am surprised it even draws anything to screen.

**Comment by linuxempire** [comment]
I try again, find set Panel bounds.w=1200,bounds.h=900,not good. but set bounds.w=600,bounds.h=600,it's good.

**Comment by vurtun** [comment]
OK I could replicate the issue. No idea what causes this behavior and where it comes from. It could be a bug in my implementation or just because of limitations of OpenGL with 2.4 MB vertex memory and 0.7 MB element memory drawn with one `glDrawElements` call. For now I have no clue what to do in this case, but I also don't think it has a high fixing priority since this kind of drawing load should not happen under normal circumstances or do you have an actual real life case this behavior caused problems? Other than that maybe somebody else knows more.

**Comment by vurtun** [comment]
OK I am an idiot. The reason why you get rendering bugs is because elements are defined as `uint16_t`. If you want to draw more data redefine `nk_draw_index` to `nk_uint` and change `glDrawElements(GL_TRIANGLES, cmd->elem_count, GL_UNSIGNED_SHORT, offset)` to `glDrawElements(GL_TRIANGLES, cmd->elem_count, GL_UNSIGNED_INT, offset)`
