### ISSUE TITLE
Functions and struct name should not be the same.

### ISSUE THREAD

**Issue by mogud** [vurtun/nuklear#169]
I'm working on an d binding of nukclear and found there are file struct's name conflict with the same name function:
nk_image
nk_vec2
nk_vec2i
nk_rect
nk_recti

dlang has a pragma(mangle, "abc") to deal with this. But IMO, this isn't a good style.

**Comment by vurtun** [comment]
Another style issue I will have to look out for in the future. The main reason I even choose the same name was to make it easier to remember their names and make the library easier to use. But like you said it turns out that this causes problems for bindings. I did not design it in the first place to be easy to bind to from other languages and only cared for C which was a mistake and something I learned from. About this problem I will probably decide in the future if I will change it in combination with other typos or if I just leave it in to not break any code.
