### ISSUE TITLE
sometimes mouse is not ungrabed

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#203]
When i try to change property created with `nk_propertyi` mouse cursor is sometimes not ungrabed. It does not happen always and i am not sure how to replicate it. I trigger it by trying to change property value while dragging. My code forces property value to same number all the time so maybe that is the problem. Anyhow sometimes mouse cursor just disappears and never reappears requiring application restart.

**Comment by vurtun** [comment]
Thanks for the issue. Which platform backend are you using? So far I only encountered this problem in SDL2 while Xlib and GLFW worked correctly. Would probably be interesting to know if even happens in the library itself or the demo code to begin with.

**Comment by rokups** [comment]
Yes indeed i am using [sdl2 ogpengl3 backend](https://github.com/vurtun/nuklear/blob/master/demo/sdl_opengl3/nuklear_sdl_gl3.h).

**Comment by star-tek-mb** [comment]
+1 for this issue. I am also using SDL2 backend with OpenGL 3.3. Slow panel/window dragging.

**Comment by star-tek-mb** [comment]
I solve this issue. There are not bug in nuklear. There are bug in code for grabbing SDL events:
Before (from SDL2 wiki):
~~~
if (SDL_PollEvent(&windowEvent)) {
~~~
After:
~~~
while (SDL_PollEvent(&windowEvent)) {
~~~
In sdl2 demo used *while*. So - there are not bug.

**Comment by vurtun** [comment]
What you could do as a short term fix is to use the software cursor which works correctly until I am able to find out how I am using SDL wrong.

**Comment by ewmailing** [comment]
I think I encountered this same problem. When I drag-click a property field to "slide" its values, sometimes I lose my mouse cursor completely and it won't come back.

I tracked this code to the mouse grab stuff at the top of the SDL binding. It is using Mouse Relative and Mouse Warp. I think this is what is causing the problem. When I remove this block of code, I no longer lose my cursor. (And I haven't noticed any feature loss.) In general, I find Mouse Warp a bad idea because I've encountered platforms where this is not supportable or just flakey. I'm a bit distrustful of relative mode too. I'm not sure which of these is the culprit (my guess is warp), but I think avoiding both these features is a good idea. I've never needed these kind of features for native GUI programming, so I think this is avoidable.
