### ISSUE TITLE
Focused text edit cuts off text top and bottom

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#204]
When `nk_edit_string` widget is not focused it renders fine:
![unfocused](https://cloud.githubusercontent.com/assets/19151258/17456330/dac3f9d8-5bdc-11e6-83f6-c6152bcaaee9.png)
But when it is focused top and bottom of text are cut-off. For example bottom of letter y is cut off as well as top of letter f.
![focused](https://cloud.githubusercontent.com/assets/19151258/17456331/dc735e9a-5bdc-11e6-89b4-70c25e40b747.png)

**Comment by vurtun** [comment]
I am not 100% sure but could you try and increase the row height. So far the only times I saw this behavior was when I set the row height to low.

**Comment by rokups** [comment]
Spot-on. This is last think i would think of because without focus all of the text is properly visible. Not sure if this still is a valid bug report, though i bet people would appreciate it if full text was visible in both cases.

**Comment by vurtun** [comment]
> i bet people would appreciate it if full text was visible in both cases

I am not quite sure it is worth doing since I combine both single- as well as multi-line in one widget so if I change the behavior to show overlapping text it would cause bugs in the multi-line edit widget. There is probably a way to hack it in there but I don't want to complicate the edit widget even more at the moment.
