### ISSUE TITLE
Way to "Grey out"/disable a widget?

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#213]
Is there a way to disable a widget without actually removing it? (Typically OS's make their widget look "greyed out".)

I'm trying to (live) validate input. For example, I modified your File Browser example to make it do "Open" and "Save". This adds buttons like Open and Save and also input filters about what file extensions are allowed. So I only want the Open/Save buttons to be enabled when the user selects a file that matches the correct extension. The rest of the time, I want the button to be disabled/greyed-out.

**Comment by vurtun** [comment]
There is no direct way to achieve what you want. But what you could do is change the style of a button to look grayed out (just temporarily change the button style inside `ctx->style.button` and don't react on user input if the file extension is not correct. If it is just draw with correct button style and react on input.

**Comment by ewmailing** [comment]
Thank you. This did the trick. 

Maybe this would be a good feature request though to make this ability more built-in, with its own preset color values (that way skin makers also provide the correct values for their disabled colors).
It's a pretty useful UI paradigm to grey-out/disable widgets based on immediate related dependencies. It's a nice way to imply feedback to the user without needing to bog down or clutter the UI with even more widgets. (It's a very common design on Mac and iOS.) And being able to provide live validation is a perfect fit with the idea of immediate mode guis.

Thanks

**Comment by dumblob** [comment]
>Maybe this would be a good feature request though to make this ability more built-in, with its own preset color values (that way skin makers also provide the correct values for their disabled colors).

**Comment by vurtun** [comment]
I am quite sure you need additional API calls. While it is easy to just add additional color attributes to each widget, forcing a widget to be grayed out and disabling it needs additional functionality. So far the reason why I did not add widget disabling is because you can just not execute a widget in a given frame if you don't want to show it (not really UX friendly). If I come up with a good API I will add it otherwise this hack won't go away.

**Comment by irtusb** [comment]
I think the proper way in immediate mode is to simply remove disabled widgets from ui and if you need to preserve layout maybe introduce some placeholder

**Comment by vurtun** [comment]
Greyed out widget have a reason to exist. They exist to not only show which action are currently possible but also which are generally possible. So if you would remove the `OK` or `Cancle` button then you would also remove information about what you could do as a user under right circumstances. In general UX is often about first defining or showing what you could do and then limit that possibility space down to what you can do at the moment. By removing widgets instead of greying them out you remove the knowledge of it even existing.
