### ISSUE TITLE
Question about energy (battery) efficiency optimization

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#225]
I'm doing some profiling on my app. I'm noticing the GUI is causing a significant amount of energy to be used. I'm wondering if there are some easy tricks to get bring down the energy consumption. 

For example, I noticed the SDL binding returns 1 for the event mapping if Nuklear might handle the event. Using this on cases where there are no changes to nk, I was thinking I might try to skip recomputing the GUI layout, and go right to re-rendering. But that led me to either asserts or rendering glitches. (I think I needed to call nk_clear before doing a new recompute pass, but trying to redraw when nothing changed still led to broken rendering).

I briefly experimented rendering the GUI to a separate texture as a cache and then combining, but aside from clipping space problems I still can't my head fully around, I was experiencing problems with alpha, transparent cracks, and weird stitching/artifacting around borders of widget elements. (However, I noticed power consumption dropped significantly.)

Anyway, I was hoping for some easy ideas on this. Thanks.

**Comment by ytsarko** [comment]
@ewmailing In the project I currently work on we are developing karaoke device controlling application. This app will let DJ to make full control of device - make up playlists, stop/pause songs and many other activities. It will execute on ARM CortexA7 CPU and will be partly software rendered for reasons I am not able to discuss (there are some limitations implied by hardware design and project management requirements).

Long story short, I am going to implement this app using nuklear toolkit. I have already done some kind of prototyping and found that CPU usage when rendering 1 app frame was quite high (my goal is to make at least 60 fps for smooth user experience). The solution was to make following optimization:

On every frame you perform usual nuklear calls (draw your buttons, edits and other visuals). All those calls add instances of **struct nk_command** (nk_command_line, nk_command_curve, nk_command_rect and so on) into nuklear`s internal command queue. In the place where you are going to draw those commands you compare this command queue with command queue from previous frame (of course you have to maintain it manually) command by command, and if these queues are equal you do nothing, ie return from drawing function. This will cause previous frame to be shown on the screen.
Practice shows that this simple technique will allow you to drastically reduce CPU usage: instead of drawing all your visuals on every frame (say 60 times per second) you only do it only few times (in the best case 1 per second) when something actually changes and all the other times show the previous frame.

In some pseudocode:

void render_scene(nk_context *ctx, struct your_state *state) {
  if (command_list_equal(ctx, state->previous_commands)) return;

  // New frame contains something new, we have to actually render it
  
  nk_foreach(cmd, nk_higo->ctx) {
     case NK_COMMAND_LINE: push_command(cmd, state); draw_line(cmd); break;
     case NK_COMMAND_RECT: push_command(cmd, state); draw_line(cmd); break;
  }
  // Here we have rendered frame and stored all its drawing commands in state
  // to check on next frame
}

**Comment by vurtun** [comment]
@ytsarko Do you really need to compare each command by itself? I had a similar idea but I would use `memcmp`. Ìf you either use `nk_init`, `nk_init_default`, `nk_init_custom` or `nk_init_fixed` you should be able to just `memcmp` the complete memory buffer inside `context::memory` up to `allocated` number of bytes.
```c
struct nk_context ctx;
void *last_buffer = calloc(1,64*1024);
nk_init_fixed(&ctx, calloc(1,64*1024), 64*1024);
/*...*/
void *commands = nk_buffer_memory(&ctx.memory);
if (memcmp(commands, last_buffer, ctx.memory.allocated)) {
    /* frame changed */
    memcpy(last_buffer, commands, ctx.memory.allocated);
    render_scene(ctx);
}
```

**Comment by ytsarko** [comment]
@vurtun
> Do you really need to compare each command by itself? I had a similar idea but I would use memcmp.

In order for this to work you must ensure that there is no padding in command structures (nk_command_line and others), otherwise you`ll end up comparing some random rubbish along with useful data.

I also tried `memcmp` approach first and quickly discovered this issue when 2 semantically (field-by-field) equal commands appeared to be non-equal bitwse.

**Comment by vurtun** [comment]
If that's the only problem then I can fix it by adding a flag which forces zeroing each command's memory before actually copying the command into it.

**Comment by ytsarko** [comment]
@vurtun Well, it is an interesting thought. I suppose that for small amount of commands/per frame (say 1-4 hundreds) it will not make any difference compared to `memcpy` approach.

I can try it with my setup and will report any differences noted (or may be will provide a PR to nuklear fixing that).

**Comment by vurtun** [comment]
I already wrote an commit for it but I don't have internet at the moment on my laptop. I will push it as soon as possible. However if you want to try it out here are the changes in `nk_command_buffer_push`:

```c
NK_INTERN void*
nk_command_buffer_push(...)
{
    /*...*/
    alignment = (nk_size)((nk_byte*)memory - (nk_byte*)unaligned);
    NK_MEMSET(cmd, 0, size + alignment);
    /*...*/
}
````
Notice that you also have to zero out any alignment that could happen.

**Comment by ytsarko** [comment]
@vurtun Thank you for such a quick reponse, I will try it out and report any findings later.

**Comment by ytsarko** [comment]
@vurtun I have tested this approach and it works nicely. I have created a [https://github.com/vurtun/nuklear/pull/253]PR) adding that.

**Comment by vurtun** [comment]
Looks good I will pull it when I get home. Hope you don't mind me asking did you measure any significant performance differences between just using `memcmp` + `memcpy` and your previously approach of directly comparing?

**Comment by ytsarko** [comment]
> did you measure any significant performance differences between just using memcmp + memcpy and your previously approach of directly comparing?

To be honest, I haven't performed any serious performance measurements using oprofile or something, but visually I didn't notice any changes. On the other side, purely theoretically, `memcmp` approach should be faster because of special compiler intrinsics, data alignment and other factors compared to more straightforward `for loop + switch` case. And, of course, few hundred lines of code folded to only 4-8, which is worth by itself :)
