### ISSUE TITLE
NK_ALIGNOF generates level 1 warning on VS2015 in C mode

### ISSUE THREAD

**Issue by mlabbe** [vurtun/nuklear#232]
Every occurrence of NK_ALIGNOF in nuklear generates this warning in VS2015 with /W1:
`warning C4116: unnamed type definition in parentheses`

This is an example of the generated preprocessor code, generated with /P:
    ```static const nk_size align = ((char*)(&((struct {char c; struct nk_command _h;}*)0)->_h) - (char*)0);```

Tested in 32-bit and 64-bit targeting Win32 when NK_IMPLEMENTATION is in a .c file.

**Comment by vurtun** [comment]
Thanks for the issue. As far as I know this is correct C code.
In C, sizeof can be applied to any type-name that is not an incomplete type (6.5.3.4p1); a struct-or-union-specifier that contains a struct declaration list (6.7.2.1p1) is a type-specifier and thus a type-name.

The reason however why MSVC throws a warning here is: 
 1. The scope of the definition may be unexpected
So basically it is only to warn and ensure programmers actually know what they are doing and
 2. While it is valid C code it is invalid C++ code and not every C++ compiler compiling C code would produce the right result. But since I have a correct version for C++ and a correct version for C I would argue that nothing wrong with my code.

**Comment by mlabbe** [comment]
Hey!  Awesome of you to get back so quickly.

I agree there's nothing wrong with *the code that's generated*, but generating warnings is less than ideal.  I ran some NK_ALIGNOF tests in C++ and C and the results are always the same on this compiler.

I can submit a pull request that does a pragma push/pop around these issues to silence the benign warnings. Thoughts?

**Comment by vurtun** [comment]
> I agree there's nothing wrong with the code that's generated, but generating warning noise is less than ideal.

Oh sorry then I misunderstood. A pull request would be desirable since I currently don't have a windows system at my disposal to make sure it works correctly.

**Comment by mlabbe** [comment]
I'll see what I can do as I get a bit deeper with Nuklear (I still haven't called a single function today).

I would strongly recommend either documenting that the library is untested on Windows and Visual Studio or at least installing Windows and VS 2015 community in a VM.

**Comment by mlabbe** [comment]
See PR #237 which fixes this issue.

**Comment by vurtun** [comment]
> I would strongly recommend either documenting that the library is untested on Windows and Visual Studio
I ran and I am running it under windows. But my windows version is not always up to date with the current library version since I changed some specifics. The reason why I asked for the PR is that I am at home and do not have access to the windows version at the moment.

**Comment by mlabbe** [comment]
Ah, gotcha. I misunderstood.  Thanks for everything!
