### ISSUE TITLE
menubar confuses layout

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#243]
I have roughly this code and it used to work proper:

```c
    if (nk_begin(nk, &layout, "TreePanel", nk_rect(0, 0, _sidebar_tree_size, graphics.GetHeight()),
                 NK_WINDOW_BORDER | NK_WINDOW_SCALABLE))
    {
        nk_layout_row_dynamic(nk, 24, 3);
        open = nk_button_label(nk, "Open") != 0;

        if (nk_button_label(nk, "Save"))
        {
                // ...
        }

        nk_layout_row_static(nk, 24, _sidebar_tree_size - 40, 1);
        nk_menubar_begin(nk);
        {
            struct nk_panel menu;
            if (nk_menu_begin_symbol_label(nk, &menu, "New UI element", 0, NK_SYMBOL_TRIANGLE_DOWN,
                                           _sidebar_tree_size - 20))
            {
                // ...
                nk_menu_end(nk);
            }
        }
        nk_menubar_end(nk);

        if (_container->GetNumChildren())
            RenderUiTree(_container->GetChild(0));
    }
    nk_end(nk);
```

This is how code above renders without tree elements:
![no-tree](https://cloud.githubusercontent.com/assets/19151258/18517631/a57d2d02-7aa5-11e6-921f-bec9583184b9.png)

This is how above code renders when tree is rendered as well:
![with-tree](https://cloud.githubusercontent.com/assets/19151258/18517632/a57f249a-7aa5-11e6-865f-068bbe26ad6b.png)
Notice how tree renders on top of [Open] and [Save] buttons. `MainMenu (Window)` is a selectable label, first item of the tree.

This is how above code with tree renders if i remove anything in-between and including `nk_menubar_begin(nk);` and `nk_menubar_end(nk);`
![no-menubar](https://cloud.githubusercontent.com/assets/19151258/18517633/a57f9740-7aa5-11e6-9dd5-b9c487de5bf4.png)

Menubar confuses layout somehow.

In case you wonder if i render tree correctly:

```c
    void UIEditor::RenderUiTree(UIElement* element)
    {
        if (!element)
            return;
    
        int32_t hash = NK_POINTER_HASH(element);
        // ...
        int active = _selected == element;
        if (nk_selectable_label(nk, name.CString(), NK_TEXT_ALIGN_LEFT, &active))
            SelectElement(active ? element : 0);
    
        if (element->GetNumChildren())
        {
            if (nk_tree_push_id(nk, NK_TREE_NODE, "Children", NK_MAXIMIZED, hash))
            {
                for (auto child : element->GetChildren())
                    RenderUiTree(child);
                nk_tree_pop(nk);
            }
        }
    }

```

Edit:
Commenting out **only** lines `nk_menubar_begin(nk);` and `nk_menubar_end(nk);` makes it render properly:
![menu-without-menubar](https://cloud.githubusercontent.com/assets/19151258/18517972/e8d73c0e-7aa6-11e6-8357-8480ea19f9c5.png)
So maybe this is not intended use after all? It used to work in the past though.

**Comment by vurtun** [comment]
From a quick overview it look like you first allocate a row and then `nk_menubar_begin`. This is wrong and not supported. What you should do:
```c
if (nk_begin(...)) {
    nk_menubar_begin(...)
    nk_layout_row_dynamic(nk, 24, 3);
    open = nk_button_label(nk, "Open") != 0;
    if (nk_button_label(nk, "Save"))
    {
        // ...
    }
    nk_menubar_end(...)
}
nk_end(...);
```
Please take note that `nk_menubar_begin` is the _first_ call that needs to happen after `nk_begin` for it to work. `nk_menubar` also does not require a `nk_layout_xxxx` call only the content inside of it. You basically can have as many rows inside the menubar as you want but don't allocate a row for the menubar itself.
I am a little bit surprised your version worked at some point since it basically destroys the scissor check like you pointed out in your screenshots. Basically I would always recommend looking at `overview.c` (you can just directly include it and call the function for demoing purposes). Hope this cleared up how to use the menubar.
