### ISSUE TITLE
Missing OSX libs in /example/Makefile?

### ISSUE THREAD

**Issue by leappeler** [vurtun/nuklear#256]
In order to successfully compile the examples, I needed to add the following to LIBS in the makefile for compilation on OSX:

-framework Cocoa -framework IOKit -framework CoreVideo

Not sure if this was just my machine or if it is a widespread problem, but I figured I'd say something in case others run into the issue!

I have not been able to get canvas working, but the others work without issue!

**Comment by PhilCK** [comment]
Just as a FYI - i didn't have this issue building the OpenGL3/SDL2 on OSX 10.11 / 10.12, not tried any of the other builds.

**Comment by PhilCK** [comment]
Yes I did have an issue, I had to add `-L /usr/local/lib -I /usr/local/include` to the make file to pickup glew and sdl

**Comment by borodust** [comment]
With `homebrew` and all dependencies installed through it, example builds simply by calling `make` after changing `glfw3` to `glfw` in the `Makefile` on my machine.

macOS Sierra, MacBook Air (13-inch, Early 2015)

**Comment by yay** [comment]
Went to Issues just to say this only to find out it's a known one. Please update the makefile as suggested!

Should be:
```
ifeq ($(UNAME_S),Darwin)
		LIBS := -lglfw3 -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -lm -lGLEW -L/usr/local/lib
```

As @borodust mentioned, `brew install glew` works well, but `brew install glfw` doesn't. Instead of renaming `glfw3` to `glfw` in the Makefile I downloaded GLFW manually and built from source (make, make install) and it worked, stumbling on missing libraries.
This is also discussed there: http://stackoverflow.com/questions/18391487/compiling-with-glfw3-linker-errors-undefined-reference
