### ISSUE TITLE
Why aren't the structs typedef'd?

### ISSUE THREAD

**Issue by aaronhyperum** [vurtun/nuklear#257]
I noticed that when using the structs in this library, they must be used with `struct name` rather than just `name`. It is somewhat inconvenient; is this some design decision that you made along the way? Or is it something that is planned to change sometime in the future?

**Comment by dumblob** [comment]
Nuklear tries to be minimalistic as much as possible. Even such "tiny" thing as typedefing structs will unnecessarily clutter it with marginal or no benefit.

Moreover, according to my broad experience with many large C code bases (JVM, Linux, Dao, Mutt, etc.), I undoubtedly prefer writing `struct name` everywhere, because of type clarity. So in the end the convenience is reversed - full type declaration doesn't hide **anything** and is only 7 characters longer (and yes, all "naming schemes" like *structs will end with `_s` and other types with `_t`* suck and add unnecessary complexity).
