### ISSUE TITLE
 WYSIWYG editor and xml-json file parse 

### ISSUE THREAD

**Issue by mumin16** [vurtun/nuklear#272]
do you plan coding a WYSIWYG  editor and xml-json file parse?
:)

**Comment by vurtun** [comment]
Probably not since my solution I would probably just look like all the other GUI libraries since it would require callbacks which I personally hate and would introduce a lot of library bloat and additional complexity. But you can easily write the library part yourself. Create a struct for every widget inside Nuklear with callbacks usually found in traditional libraries. Then use a parser library to allocate and create one of your struct and link the callback. Finally you just have to run over each widget and call it.
