### ISSUE TITLE
Sluggish performance on Linux

### ISSUE THREAD

**Issue by karai17** [vurtun/nuklear#297]
When running the x11opengl3 demo, I get sluggish performance where dragging a simple window around causes the window to lag behind my cursor. In the below video, I am using the Lua binding in a game framework, but the performance is the same. Excuse the blinking in the video, OBS is giving me a hard time recently.

https://youtu.be/pOtH4pd3E-k

Is this expected behaviour, or is some bad mojo going on?

**Comment by vurtun** [comment]
Thanks for the issue. The sluggish behavior is normal and there is nothing I can do about it. The reason is pretty simple your cursor is a hardware cursor and is perfectly drawn by the OS. There just is now direct way for me to beat the hardware cursor in drawing speed. This is the reason why all games have their own software cursor and the reason why I support drawing and baking a software cursor. What you could as well if you want to be real fancy is to use a hardware cursor by default and on drag operation switch to software cursor.

**Comment by karai17** [comment]
Thanks for the quick response. That makes perfect sense, yeah.
