### ISSUE TITLE
API changed again?

### ISSUE THREAD

**Issue by fr500** [vurtun/nuklear#300]
I haven't updated for a while, since 1.00, I thought the API was gonna stay relatively stable so I updated today and I get a lot of build errors:

http://hastebin.com/otacozevol.cs

I can fix them I guess, I'll have to look at all these functions and correct them but I wonder, is this expected to happen on every update?

**Comment by dumblob** [comment]
Nuklear is apparently not using a firm versioning scheme/method, so currently I would expect API changes in **each** released "version" where version is the string between the two dash characters in the first comment of `nuklear.h` (`Nuklear - v1.18 - public domain`).

I raised a question about this in https://github.com/vurtun/nuklear/issues/183#issuecomment-237022133 , but so far no response :( .

**Comment by vurtun** [comment]
@fr500 I removed the need to provide `nk_panel` which is the main breaking API change as far as I can remember. The second change is that I removed the need to pass button behavior to every button function. That should be all breaking changes the last 10 month. So it is not like I completely rewrote the whole API every few weeks or month. As for additional API changes in the future there probably won't be any. At least at the moment I just don't have any time to really work on nuklear and the time I can spare is mostly invested in fixing bugs.

As for the versioning system @dumblob, I have a system in place so it is not like the version numbers are just random. At least so far for me the version was X.Y.Z with X major version only really big changes, Y for breaking or purely additive changes with extra notes inside the CHANGELOG if it is a breaking changes and finally Z if it is just a bug fix and does not break or add anything. Each number X,Y,Z is growing upwards with each level on the left resetting all values on the right back to zero if changed.

**Comment by dumblob** [comment]
@vurtun thanks for the description of the current versioning. Could you please mention this versioning definition in README? It sounds very similar to Semver with just three visible differences:

1. Semver requires using the "full version" string even if the `Z` number is `0` (i.e. `1.0.0` instead of `1.0`).

1. Semver uses always the shortest possible writing variant of each particular number - without any prefixes etc. (i.e. `1.0.0` instead of `1.00.00`).

1. Semver does not use any prefix like `v` as in Nuklear (i.e. `1.0.0` instead of `v1.0.0`).

Feel free to accommodate these visible changes (without changing the meaning you described, which is more or less compatible with Semver) and make the world further slightly more consistent :wink:.

**Comment by fr500** [comment]
@vurtun thanks for your response I wasn't implying you changed the api completely
