### ISSUE TITLE
Suspicious definition of `points` in `nk_command_polygon`

### ISSUE THREAD

**Issue by borodust** [vurtun/nuklear#303]
`points` field is defined in a suspicious way in `nk_command_polygon` structure. Is this code correct? 
I'm not exactly versed in the C lang, so I apologize if I misinterpreted the code in the wrong way. If it is correct though, could you, please, explain why it is defined in this way?

https://github.com/vurtun/nuklear/blob/0273b7cf4cd21b2bb306c2d04b8915fb0b7667e8/nuklear.h#L1894

Excerpt:
```c
struct nk_command_polygon {
    struct nk_command header;
    struct nk_color color;
    unsigned short line_thickness;
    unsigned short point_count;
    struct nk_vec2i points[1]; // static array with one element?
};
```

**Comment by vurtun** [comment]
Yes the code is correct and the behavior is wanted and even needed. Basically ANSI C (C90) does not have zero length arrays so I have to define an array with one dummy element.

The reason why this works is because this struct will be stored along side all the other commands inside one big memory block which assures that all array access outside the one element will hit valid memory since I reserve enough memory beforehand.

This is an old and one of many well known tricks to get around some limitations of C90.

**Comment by borodust** [comment]
Thank you very much for the explanation!
