### ISSUE TITLE
window close-button can not close windows?

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#304]
when I want to close overview window,but mouse click can not close window, then window will move left align as below pic, how to sovle this question for me ?
![001](https://cloud.githubusercontent.com/assets/905931/21470271/b54442d2-cabb-11e6-99e3-826d3c7b2207.jpg)
when  I collapse this window,then click close-button, it can close windows,why?
![002](https://cloud.githubusercontent.com/assets/905931/21470273/c4dc15c6-cabb-11e6-82a9-1ce2d316f7c5.jpg)

**Comment by vurtun** [comment]
Hey and thanks for the issue. As far as I can tell you are using my default demo which does not implement window closing (I explicitly don't have a checkbox for 'NK_WINDOW_CLOSABLE'). The reason is pretty simple if you want to close a window then you can just not execute the window code.

So basically you need a flag to check if a certain window is open or closed and if the window was closed. You can check if the window was closed by calling `nk_window_is_closed` and from there on don't call the code which executes the window anymore.

For a quick example:
```c
/* ... */
struct nk_context *ctx = /* ... */;
int window_open = 1;
/* ... */
while (1) {
    if (window_open)
        overview(ctx);
    window_open = nk_window_is_closed(ctx, "Overview") == 0;
}
```
