### ISSUE TITLE
Use FreeType instead of the Stb libraries

### ISSUE THREAD

**Issue by TheServer201** [vurtun/nuklear#307]
I want to use the FreeType library in my code but :
- There is no bin packing in this library (and the one used in the Stb is bad)
- How to make an atlas (I already done char by char but dunno how to make the whole charset)

**Comment by vurtun** [comment]
I am probably not the right one to ask how FreeType works. At one time this library actually used FreeType but this is 1 1/2 years ago so I don't remember how to setup and actually get FreeType to run anymore.
As of how to add FreeType to this library I wrote a little bit about it inside `nuklear.h` (in the font section). There are three different ways depending how much control you want. This library actually only requires the font atlas texture and one or two callbacks for text width calculation and a query callback to get single glyph information.
I really don't know how I should answer since I am not an expert in FreeType.

**Comment by TheServer201** [comment]
Actually I use this code for atlas : https://gitlab.com/wikibooks-opengl/modern-tutorials/blob/master/text02_atlas/text.cpp
I think I will upload the atlas to memory instead of opengl and see your callbacks. 
It would be great if I find the old version.
