### ISSUE TITLE
how to add window main menu?

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#308]
how to add application main menu using nuklear as below?
![360 20161228123356811](https://cloud.githubusercontent.com/assets/905931/21513980/ed14f356-ccf9-11e6-93cd-0fd03479984c.jpg)
Will  increase the function of the main menu  in the future?

**Comment by metiscus** [comment]
The library does not directly support doing that but there are a few ways to accomplish what you want. As an example, you can embed the nuklear drawing context into a native (or a platform agnostic window toolkit like Qt or wxWidgets) window and use the menu functionality while drawing the nuklear widgets into the client space of the window.

**Comment by vurtun** [comment]
Please have a look into `demo/overview.c` or `demo/sdl_opengl3/main.c` (just search for `nk_menubar` and `nk_menu_begin) to see how menu work in nuklear. Basically menus and menubars can contain every kind of widget so you even could have graphs inside your menus so I don't think there is a direct need to extend the menu system. However there is one limitation. Menu cannot be nested. So you only can have *one* open menu/popup window at a time. This is basically a limitation of my decision allow users to only pass a memory block and everything works. I will not change it since it would mean that I have to change a lot inside the library which I don't want at this point in time.
If you have any more specific problems feel free to ask away.

**Comment by zhouxs1023** [comment]
Thanks a lot!
