### ISSUE TITLE
No nk_buffer_free for buffers in OpenGL3 backend

### ISSUE THREAD

**Issue by xlab** [vurtun/nuklear#317]
Hi, I spotted this difference between OpenGL3 and OpenGL2 backend demos, the buffers allocated are freed in GL2 but not in GL3. Is it a potential leak in GL3 or just a precaution in GL2?
 
https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl2/nuklear_glfw_gl2.h#L168-L169

### opengl2

```C
        nk_buffer_init_default(&vbuf);
        nk_buffer_init_default(&ebuf);
        nk_convert(&glfw.ctx, &dev->cmds, &vbuf, &ebuf, &config);

        // draw here

        nk_clear(&glfw.ctx);
        nk_buffer_free(&vbuf);
        nk_buffer_free(&ebuf);
```

### opengl3

https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/nuklear_glfw_gl3.h#L287

**Comment by vurtun** [comment]
Thanks for the issue but OpenGL 3 does not allocated any memory for vertexes and elements but instead just maps and unmaps opengl buffers so after you `nk_convert` you don't have to free any memory, only unmap opengl buffers. 
Since OpenGL does not provide a way to map buffers I have to directly allocate and free buffer memory. So basically I would recommend always using OpenGL 3 if possible.
