### ISSUE TITLE
How to make cascading menu (such two level,three level menu）?

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#346]
How to make cascading menu as below pics ? 

![menu](https://cloud.githubusercontent.com/assets/905931/23103500/ef0a32e4-f6f6-11e6-89a4-d1cb35dc812d.PNG)

**Comment by vurtun** [comment]
Nuklear does not support cascading menu. It was a technical decision rather early in the design process. Basically it is not possible to create popups inside popups. It is a limitation but it simplifies the architecture a lot. At this point it is not really possible to add it since it would require a big core chunk to be rewritten with a least in my opinion little benefit.

The big advantage of immediate mode UI is that you can change everything just by adding conditions. So there is no need for cascading menus. You can just change the content of the menu if an item was selected. Basically something like this:

```c
enum menu_state {DEFAULT, WINDOWS};
static enum menu_state state = DEFAULT;
nk_menubar_begin(ctx);
if (nk_menu_begin_label(ctx, "MENU", NK_TEXT_LEFT, nk_vec2(120, 200)))
{
    if (state == DEFAULT) {
        if (nk_menu_item_label(ctx, "WINDOWS", NK_TEXT_LEFT))
            state = WINDOWS;
    } else if (state == WINDOWS) {
        if (nk_menu_item_label(ctx, "BACK", NK_TEXT_LEFT))
            state = DEFAULT;
    }
    nk_menu_end(ctx);
}
nk_menubar_end(ctx);
```

**Comment by dumblob** [comment]
@zhouxs1023 you might consider the approach suggested in https://github.com/vurtun/nuklear/issues/119#issuecomment-216272342 .
