### ISSUE TITLE
Unions like nk_handle should have tags

### ISSUE THREAD

**Issue by zacharycarter** [vurtun/nuklear#351]
Unions like nk_handle could really use tags.

It's problematic and difficult to determine what type occupies the memory of nk_handle at runtime. This causes an issue with my graphics API (BGFX). BGFX has a SetTexture method which accepts an object of a type TextureHandle that contains a single member - idx.

I can't determine whether to cast nk_handle.ptr into a TextureHandle or an int after I've assigned a value to this union. It would be nice if I could have a tag to check what type was assigned to - the pointer field or the int field. Until then, I am left with ugly and error prone code like (sorry it's in Nim as usual):

note - cmd.texture.pointr = nk_draw_command.texture.ptr
```
        if not cmd.texture.pointr.isNil:
          let texId = cast[cint](cmd.texture.pointr)
          var texHandle = TextureHandle(idx: uint16_t texId)
          if isValid(texHandle):
            SetTexture(0, nkbgfx.dev.uh, texHandle)
          else:
            texHandle = cast[ptr TextureHandle](cmd.texture.pointr)[]
            SetTexture(0, nkbgfx.dev.uh, texHandle)
```
Also I think this could be avoided entirely via the use of - (u)intptr_t which will correctly be sized to the size of a pointer on the target platform and be usable as an integer for doing pointer arithmetic.

Please let me know what you think.

**Comment by vurtun** [comment]
So if I understand correctly BGFX uses the same trick as nuklear of using both an ID and pointer for handles. So the question is who needs to change BFGX or nuklear. Since I already have construct functions that distinguish between pointer and ID to probably makes sense to change my implementation.

 As for `intptr_t` that would be what I would if I would write it again now as well. The question is if I can just change it now. In theory sure since I provide creation functions `nk_handle_ptr` and `nk_handle_id`. Problem however is that I cannot guarantee that everybody uses them and instead fills them directly. So the general options are:

1.) Adding a type tag which increases the size of the union
2.) Retype `nk_handle` to `intptr_t` and break code (especially bindings)
3.) Change the `int` inside the union to an `intptr_t`
4.) Leave it as it is and let corner cases be corner cases

My personal preference would be (3). Since it does not break anything while still hopefully making
bindings easier.

**Comment by dumblob** [comment]
I'm raising my hand for (3).

**Comment by zacharycarter** [comment]
Almost, but not quite. Let me do a better job of explaining - sorry my fault.

BGFX defines this type - https://github.com/bkaradzic/bgfx/blob/master/include/bgfx/c99/bgfx.h#L258

So essentially every BGFX handle (a texture handle, shader handle, etc...) will be a struct with a single idx member property of type uint16.

BGFX allows you to set the current texture handle through this function call:
https://github.com/bkaradzic/bgfx/blob/master/include/bgfx/c99/bgfx.h#L867

So when I'm iterating over my draw commands, my code looks similar to this -
```
# Get first draw command via nk_draw_begin
var cmd : ptr nk_draw_command = nk_draw_begin(addr nkbgfx.ctx, addr nkbgfx.dev.cmds)
      
      # While there are more draw commands, draw
      while not isNil(cmd):
        SetState( BGFX_STATE_RGB_WRITE or BGFX_STATE_ALPHA_WRITE or
                            BGFX_STATE_BLEND_FUNC( BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA ) )

        # Check if the union is nil or not
        if not cmd.texture.pointr.isNil:
          # Assume the union holds an int
          SetTexture(0, nkbgfx.dev.uh, TextureHandle(idx: uint16 cmd.texture.id))
        else:
          # Texture is nil - use default font handle
          SetTexture(0, nkbgfx.dev.uh, nkbgfx.dev.fontAtlasHandle)

        SetVertexBuffer( addr tvb )
        SetIndexBuffer( addr tib, offset, cmd.elem_count)

        Submit(0, nkbgfx.dev.sph)

        offset += cmd.elem_count

        cmd = nk_draw_next(cmd, addr nkbgfx.dev.cmds, addr nkbgfx.ctx)
```

This works, because I know I'm always calling nk_image_id | nk_handle_id to create my nk_image and nk_handle objects. If however, I were to start calling nk_handle_ptr | nk_image_ptr, I'd be somewhat screwed in my checks - I wouldn't know whether to cast cmd.texture into a pointer to a TextureHandle object or assign its value to the idx property of a TextureHandle object.

Thinking about it further, I don't think (3) will address this issue for me. I think the solution for me is going to be to change my bindings to map the union to a Nim pointer, that way I can always treat nk_handle as a pointer. That may be the solution here for others binding as well.

(3) would still be helpful though for potentially other drawing APIs that are doing the same thing tick as you for texture handles @vurtun 

I guess we can leave this open and see what more folks have to say?

**Comment by dumblob** [comment]
>For now my solution is going to be that, until I can find a better way. I'm the only one using my BGFX backend so this shouldn't be too much of a problem for me.

Is there any performance penalty or is it just about readability/convenience?

**Comment by zacharycarter** [comment]
It's neither - it's more about clear API function.

Because I don't know what the union contains when iterating over draw calls I'm left to assume that it's either a pointer to an object (in my case a TextureHandle) or a texture handle ID and NOT a pointer.

This means I have to always submit using pointers or IDs unless I want to have to try to make this determination at runtime which is currently impossible.

It's not about convenience or performance, it's more about being able to reliably determine what nk_handle actually represents.

**Comment by dumblob** [comment]
@zacharycarter I've asked, because this is clearly a limitation of Nim and its support for pointers. It seems Nim forces one (presumably because of the Nim type system) to cast from a pointer to number (the "Nim type metadata" are thus lost because the programmer deliberately chose so), first then save the resulting number to the nuklear structure and, no comes the part you've copy-pasted in the initial post, after reading this number back, the original "Nim type metadata" are lost.

I would recommend wrapping `nk_handle` by some Nim data wrappers holding this additional type metadata information (which are anyway added and required by Nim, not Nuklear). Thinking about it, Nim templates might be enough if carefully used (Nim templates operate on the AST level if I'm not mistaken).

**Comment by zacharycarter** [comment]
@dumblob maybe I'm missing something then, as Nim isn't forcing me to cast a pointer into anything (and if I am I apologize ahead of time).

Consider the following example in Nim :

```
import nuklear

type
  TextureHandle = object
    id: int

var nkimg : nuk_image
var nkimg2 : nuk_image
var texHandle : TextureHandle = TextureHandle(id:1)
var texId: cint = 1

nkimg = nk_image_ptr(addr texHandle)
nkimg2 = nk_image_id(texId)

echo repr cast[ptr TextureHandle](nkimg.handle)[]
echo repr nkimg2.handle
```

The only cast I'm making is - ```cast[ptr TextureHandle](nkimg.handle)[]``` which casts the pointer into a pointer to a TextureHandle (which it is) and then I'm dereferencing the pointer using the Nim dereference operator : []

You'll notice no casts on nkimg2 which holds the integral value. The output of the program is as follows:
```
➜  C nim c -r test.nim
Hint: used config file '/Users/zachcarter/projects/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: nuklear [Processing]
Hint: macros [Processing]
CC: test
CC: stdlib_system
Hint:  [Link]
Hint: operation successful (13944 lines compiled; 0.480 sec total; 22.422MiB peekmem; Debug Build) [SuccessX]
Hint: /Users/zachcarter/projects/bearlibterminal/Terminal/Include/C/test  [Exec]
**[id = 1]**

**0x1**
```

So without any casts the handle reflects an integral value. If I was using OpenGL I'd be fine - I could simply always pass nk_image.handle to glBindTeture(), as the drawing API accepts an unsigned integer. BGFX wants a TextureHandle object it has defined, and again, it's impossible to determine at runtime what nk_handle holds - Nim | C | insert whatever other language here.

**Comment by dumblob** [comment]
@zacharycarter thank you for the nice summary. Let me briefly mention few things which popped in my head.

1. BGFG TextureHandle is a shallow binding of a C structure to Nim (with the same interface as you outlined in [your example above](https://github.com/vurtun/nuklear/issues/351#issuecomment-283034434 )).
1. Nim by default passes everything by value (internally though it might_be/is by reference for speed).
1. Nuklear uses a union because there is no need to distinguish the saved data (an integer from a pointer), because both are just passed to corresponding functions, which shall be matched based on the `NK_COMMAND_` which is being performed.
1. Nims `addr` is meant mainly (if not solely) for interfacing with C to ensure the C code will "see" a pointer.

In the initial example in this thread you're actually mixing a **high**-level Nim representation of the low-level BGFX API with **low**-level Nim representation of the low-level Nuklear API. This approach is not only non-Nimian, but it's technically a bad idea in general for any high-level language which does not have pointer support as first class citizens (i.e. as a part on which the whole language depends and thus this part can't be removed; Nim language with its minimal bundled stuff does not depend on pointer support). Therefore these issues and therefore I wrote it's a limitation of Nim (in other words the limitation is, that Nim does not separate clearly enough its first-class stuff from additional stuff like pointers).

A technically fitting solution is thus to forget about pointers and to create the Nuklear Nim binding high-level enough, so that the programmer does not need to deal with pointers. That usually means clever wrapping - as shallow as possible (for performance reasons) while not separately wrapping each tiny structure meant to be instantiated many times (because of GC pressure).

**Comment by zacharycarter** [comment]
Your reply makes sense @dumblob thank you for taking the time to elaborate on it for me, much appreciated. I'll go ahead and close this now.
