### ISSUE TITLE
Popup is blocked by other windows when menubar windows using NK_WINDOW_BACKGROUND  flags 

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#378]
![360 16290619104138137](https://cloud.githubusercontent.com/assets/905931/24252103/779bfe92-1017-11e7-89b7-6b5607480ccb.png)
I create  main menu using flags:NK_WINDOW_BACKGROUND,but popup window is blocked by other window as pics?

**Comment by vurtun** [comment]
This looks like a fuck up on my part. To fix this I need to pull popups out of window management and put them inside their own top level layer to make this work. While it could simplify some code it could require some hairy changes. Window and popup draw commands are interleaved and fixed up after the window was finished. These changes would move the fix up to the end of the frame. When I have some time I will try to fix or at least check how many and how complex the changes are.

**Comment by S-ed** [comment]
Isn't it possible to just let popups ignore NK_WINDOW_BACKGROUND flag?
Also...You have a stack of contextual popups?

**Comment by vurtun** [comment]
It is not that simple sadly. The main reason is `nk_init_fixed`. The complete library can be fueled with only one block of memory. This is something actually I have never seen in any other library and it was a lot of work to get everything to work under this constraint. 

One end of the memory block is filled with draw commands `|C1|C2|C3|...` with each panel storing first and last command offset. The other end is filled with windows, panels and tables `...|P2|P1||T2|W2|W1|`. 

Note that this design so far has no concept for popups. Each popup is made out of draw commands as well but these need to be executed later then the main window draw commands. But here is the problem popups are declared inside `nk_begin` and `nk_end`. So popups therefore create nested windows. For draw commands that means that your window draw commands are split up into two and between these to parts are popup draw commands `|Window1||Popup|Window1|Window2|...|`. In the end for each window on `nk_end` the list of draw commands is fixed up so that the window draw commands are drawn first and the popup draw commands later. `|Window1|Window1|Popup|Window2|...|`.

But this introduces the problem above. Popups are linked to their owning windows. But this is wrong. They need to be linked after all windows. So instead of `Window1|Popup1|Window2` it needs to be
`Window1|Window2|...|Popup1`. So instead of fixing up draw commands in `nk_end` it needs to fixed up at the end of the frame in `nk_build`.

**Comment by S-ed** [comment]
Yeah, I thought that popup may be attached to it's parent (sorry, only have read like 5% of the code).
I wondering, why Popups has it's own implementation. I mean, why are those not windows? Performance wise?

**Comment by vurtun** [comment]
@zhouxs1023 OK I think I fixed it. Could you test again if it works correctly now?

@S-ed Because at the draw command level layer there is no concept of windows or popups. Only draw commands which need to be in a correct drawing order. So making popups to windows does not solve anything and only requires more memory for each popup (reasons in last comment). If I really want to make popups to windows I would need to allocate a growing draw command list for every window. This in terms would mean that I have to remove `nk_init_fixed` and `nk_init_custom` which would take away memory control from the user.

**Comment by S-ed** [comment]
@vurtun I thought windows could only be added to the top (or bottom) unlike Popups.
Sorry for disturbing. And thanks for your time.

**Comment by zhouxs1023** [comment]
Solved :),pics as below,Thanks you
![165811261009492](https://cloud.githubusercontent.com/assets/905931/24323548/43553742-11b2-11e7-8049-a06c5ce79064.png)
