### ISSUE TITLE
Multiple buttons added to row layout permit simultaneous hover/click

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#405]
Hello,

adding multiple buttons to a single-column row-layout (i guess it is inpendent of column count) using zero padding/spacing allow 2 consecutive buttons being highlighted and clicked simultaneously if the mouse is placed between the 2 buttons in question. There is a single pixel-row between every 2 buttons where this behaviour happens.

Cheers.

**Comment by vurtun** [comment]
Thanks for the issue I found the bug and fixed it and will push it asap. The bug was inside `NK_BETWEEN` inside `NK_INBOX` and is based on the fact that pixels are index based. So instead of `<=` I have to check for `<`. However since this affects both height and width I also had to decrement row width by one. No sure if this is 100% correct but if anyone has a better idea feel free to tell me.
