### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by Rykehuss** [vurtun/nuklear#415]
Can someone explain me how set utf-8 encoding characters in window/button/etc titles?
All my attempts give me nothing.
![nuklear_utf8](https://cloud.githubusercontent.com/assets/25252276/25195164/69bcb80a-2545-11e7-83c7-99ae48d39467.png)

I find functions
`/* UTF-8 */`
`NK_API int                      nk_utf_decode(const char*, nk_rune*, int);`
`NK_API int                      nk_utf_encode(nk_rune, char*, int);`
`NK_API int                      nk_utf_len(const char*, int byte_len);`
`NK_API const char*              nk_utf_at(const char *buffer, int length, int index, nk_rune *unicode, int *len);`
in nuklear.h, but have no idea how use it.

**Comment by vurtun** [comment]
Since this look like you are using one of the OpenGL demos please read #211.

**Comment by Rykehuss** [comment]
Thanks for help, now all works. I think, I will do page in Nuklear wiki for other users.

**Comment by Rykehuss** [comment]
Done! https://github.com/vurtun/nuklear/wiki/UTF-8-Support

**Comment by dumblob** [comment]
@Rykehuss thanks for the effort. Could you please also add descriptions to magic constants (I'm refering to the integer `14` at two places)?

Also consider using C99/C89 syntax for UTF-8 string literals instead of the C++ version `u8"this is a C++ always UTF-8 literal"` (I didn't test it, but until now I thought Nuklear does not require the string to be encoded as UTF-8 in case the environment in which the compiled program runs is not set to UTF-8; if I'm correct, then you can use plain C strings `"this is a plain C string literal"`).

**Comment by Rykehuss** [comment]
Done.
Maybe I made some mistakes, because I haven't other compilers except VStudio 2017 in which "plain C string literal with utf-8 chars" not worked.
Exact works versions with load string at runtime and with using u8 string literal (yes, i know it's C++17 feature, but it works in VStudio 2017).
If someone know other solutions - please, add it to article.

**Comment by dumblob** [comment]
@Rykehuss thank you, it's perfectly clear now!

Note: the link in the [comment above](https://github.com/vurtun/nuklear/issues/415#issuecomment-295732054 ) stopped working as now the URL is `https://github.com/vurtun/nuklear/wiki/UTF%E2%80%908-Support` - note the weird character instead of plain ASCII "-". Could you please rename it back to the ASCII variant?

**Comment by Rykehuss** [comment]
@dumblob of, course.

Reason for change article title was that wiki engine "ate" hyphen from title.

And thanks for feedback.
