### ISSUE TITLE
widgets with adpative width

### ISSUE THREAD

**Issue by thatname** [vurtun/nuklear#427]
Is it possible to have a labeled button, whose width is computed from its label's width?
dear Imgui computes it for every button automatically.

**Comment by ventosus** [comment]
@thatname you can calculate label width beforehand via *nk_user_font->width*

    const struct nk_user_font *font = ctx->style.font;
    const char *str = "hello world";
    const size_t str_len = strlen(str);
    const float fw = font->width(font->userdata, font->height, str, str_len);

**Comment by vurtun** [comment]
@thatname I deliberately don't have auto sizing for widgets since nuklears layouting works different to dear imgui. Like @ventosus said you can create your own version for specific layouting APIs, but I don't have a general purpose solution. In theory `nk_config` could contain default sizes for each widget and I could introduce a `default` layouting scheme. But even that solution has problems.
