### ISSUE TITLE
bug with buttons and small windows

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#442]
It seems buttons (and possibly other widgets?) don't register mouse events when they are partially obscured by being too large for the window.

Example code:
```c
if (nk_begin(ctx, "Demo", nk_rect(50, 50, 200, 200),
    NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|
    NK_WINDOW_CLOSABLE|NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE))
{
	nk_layout_row_begin(ctx, NK_STATIC, 25, 2);
	{
		nk_layout_row_push(ctx, 220);

		if (nk_button_label(ctx, "BUTTON", NK_TEXT_CENTERED))
			printf("asdasd");
	}
        nk_layout_row_end(ctx);
}
nk_end(ctx);
```

And the behaviour:
![nk_button_bug](https://cloud.githubusercontent.com/assets/1093274/26352510/0a1632b2-3fb4-11e7-8401-9258512a05d7.gif)

**Comment by wheybags** [comment]
Sorry to bombard you with issues today :p

**Comment by vurtun** [comment]
No problem.  Basically as long as any issue tries to help me by providing the two important pieces of information I have no problems looking into it: 

1.  What is wrong. Preferably with screenshot or gif like in your case
2. What should be the correct behavior

If these two are met there is a high change that I can help out since I only have to find the source of the problem and fix it. 

For example in your case the second is not exactly clear for me. The problem here is that I have to prevent widgets from being interactive while scrolling to make sure you cannot interact with them outside window bounds.

So while it is possible to basically calculate two rectangles for each widget with both actual space as well as visual space it would require me to rewrite every widget to take account for that. I will take a look and see how much work it is to fix.

**Comment by vurtun** [comment]
Scratch everything I said. Past me is just an idiot and failed to see the obvious solution. Hopefully should be fixed now.

**Comment by wheybags** [comment]
Works fine for me, thanks again!
