### ISSUE TITLE
Launching a window from within a window.

### ISSUE THREAD

**Issue by techfreakworm** [vurtun/nuklear#451]
@vurtun Your library is truly awesome. Great work. I even got selected to make a NUKLEAR GUI for CCExtractor as GSoC project. There is one problem I'm struggling with for a few days.
Is it a functionality that nuklear lacks or am I missing something?
I'm using GLFW and GLEW as back-end.
I created a window, nuklear context, a button using `nk_button_label` in same context and everything works fine. But, when I use that button to trigger another `GLFWwindow` it does work only if it's empty, which means it has no `nk_context` in it. Moreover, the blank Window launches and closes as needed but when closed, the Parent window stops updating the Widgets, as if looping has stopped. But it hasn't, since event handling works.
When I try to create a `nk_context` inside the child Window, just triggering it stops the whole program.
I went through all the examples and demo but none of them have used more than one window in a program.

Complete code for the program with problem is on: https://github.com/techfreakworm/ccextractorGUI-nuklear
Go to Help->About CCExtractor (This triggers another `GLFWwindow`)

Just Comment out lines: 211 to 213 AND 220 to 226. To confirm the that `GLFWwindow` works and leads to a non-updating Parent Window.

Any Help is appreciated.  Thanks!

**Comment by vurtun** [comment]
> Is it a functionality that nuklear lacks or am I missing something?
I'm using GLFW and GLEW as back-end.

The default demo backends currently do not support multiple windows. The reason was that I wrote the basic design a year ago in crunch time over two days and it stuck. In general the `nk_glfw` state inside `nuklear_glfw_gl3.h` is a global variable and would have to be converted into a state object like `nk_context` and passed to all functions to make it possible to have multiple OS windows.

I also took a peek inside your [code](https://github.com/techfreakworm/ccextractorGUI-nuklear/blob/master/ccextractorGUI.c#L205). This is wrong. The context returned from `nk_glfw_init` is _NOT_ a `GLFWwindow` usable by `glfwMakeContextCurrent`. It is a nuklear context.

The `glfwMakeContextCurrent` call only works on `GLFWwindows` that you have to create yourself. So at this point you either have to modify the GLFW demo to support multiple OS windows or you could use nuklear internal popups to display your about panel (I have an example of that inside `overview.c`) depending on your requirements.

**Comment by techfreakworm** [comment]
@vurtun Thanks for the help and your time. I really  appreciate that. :)
