### ISSUE TITLE
nk_group_scrolled_offset_begin and nk_group_scrolled_begin

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#461]
Sorry to bother you again, but I'm not sure what exactly these two functions do, and I couldn't find any examples anywhere.
On a side note, I'd love to help with documenting the parts of nuklear that I do understand, (not documenting funtions the way you are doing in the header, but more like wiki-style documentation).
Is there a plan for something like that, and if so, should it be on the github wiki or somewhere else?

**Comment by vurtun** [comment]
> Sorry to bother you again, but I'm not sure what exactly these two functions do, and I couldn't find any examples anywhere.

`nk_group_begin`, `nk_group_scrolled_offset_begin` and `nk_group_scrolled_begin` are all the same. The only difference is that the last two do not store any scrollbar state inside nuklear. The reason why there are two if explicit scrollbar offsets is because of legacy reasons since I did not want to break the API. 

> On a side note, I'd love to help with documenting the parts of nuklear that I do understand, (not documenting funtions the way you are doing in the header, but more like wiki-style documentation).
Is there a plan for something like that, and if so, should it be on the github wiki or somewhere else?

There is but I would prefer if all documentation to be inside `nuklear.h`. It general there is "hard" documentation (function and parameter descriptions)  and "soft" documentation in form of general descriptions like explanation how it is possible to only update on user input or how to use certain functions or APIs as a unit. So if I understand correctly what you want could fit into "soft" documentation which could be added to `nuklear.h` as well.

**Comment by wheybags** [comment]
Ah, ok, that makes sense. As for documentation,   i was hiking of including a bunch of screenshots included, so that wouldn't really work inside a header. I was thinking of a "soft" q&a style of documentation, like "how do I draw an image", and "how do I do layouts".

**Comment by vurtun** [comment]
> I was thinking of a "soft" q&a style of documentation, like "how do I draw an image", and "how do I do layouts".

Sounds fitting for me. In general how I had planned to write documentation was for each function to have both hard documentation and a small example showing how to use it. At least for all widget and layout specific functions.

**Comment by wheybags** [comment]
Can I ask which of the two functions is the legacy version?

**Comment by vurtun** [comment]
The legacy version is `nk_group_scrolled_offset_begin` as far as I remember. It also implements the actual `nk_group` functionality and `nk_group_begin` and `nk_group_scrolled_begin` only call it with their specific arguments.
