### ISSUE TITLE
Visual border drag with nk_window_set_position and nk_window_set_size 

### ISSUE THREAD

**Issue by Kernle32DLL** [vurtun/nuklear#517]
Something I noticed while toying around with nuklear. Apparently, functions like _nk_window_set_position_ do not correctly update the window layout, as using said method causes visual artifacts when using borders.

What happens behind the curtains is that _nk_window_set_position_ updates the window bounds (window->bounds), causing the border to be drawn at the **new** position when _nk_end_ is issued. However, all other drawing commands operate on the **layout** bounds (window->layout->bounds). Which effectively means that everything but the borders are drawn at the **old** position, which is in line with what was issued in _nk_begin_.

In practice, this causes drawing such as this:
![screenshot at 2017-09-13 18 23 31](https://user-images.githubusercontent.com/1338408/30388994-d805f742-98b1-11e7-9881-d818b4e67fb3.png)

There are some possible fixes I identified, without digging to deep into the code base:

1. Update window->layout->bounds when issuing any positional or size changes to a window (probabl impossible, as  window->layout->bounds is calculated in _nk_begin_ by some constraints, and probably modified by subsequent ui elements of the window)
2. Implement some way to modify a window position or layout outside the current context (probably out of scope of this lib, as such functionality would apply to all elements, not just windows)
3. Defer layout changes to the window, so the border is drawn at the old position
4. Move border drawing into _nk_begin_

I did successfully implement 4, but I refrained from issuing a PR as I don't know it there is a reason borders are drawn in _nk_end_ instead of _nk_begin_

**Comment by vurtun** [comment]
Hey, thanks for the issue.

That is a bad blunder on my side. Sadly there is no non-breaking API change. The reason is that border drawing is required to be drawn in `nk_end` because of dynamically growing popups which only know their size at the end of the frame. There may  be a way to hack in a solution that only updates position and size in `nk_end` but honestly it would complicate the whole thing even more and turn it even more into a nightmare to maintain.

So I decided to introduce the first breaking change so far in this versioning scheme. Now all window  modifying functions take in  a window name and are prevented to be called while the window itself is being processed by assert.

**Comment by Kernle32DLL** [comment]
@vurtun Wow... sorry. I wouldn't have thought that this would have such deep implications. But thanks for the quick fix! I will give it a spin later today.

**Comment by Kernle32DLL** [comment]
@vurtun Small oversight. You still try to update ctx->current->bounds in _nk_window_set_bounds_, instead of win->bounds (see https://github.com/vurtun/nuklear/commit/3b5123f523540eb9cec02b0faf0d234409aefebc#diff-54af4b6cab9b8bb5a911bbc6b9f4a21aL18946)

**Comment by vurtun** [comment]
Thanks. Hopefully now fixed.

**Comment by Kernle32DLL** [comment]
@vurtun Works as far as I can tell, thanks!
