### ISSUE TITLE
Window clipping

### ISSUE THREAD

**Issue by fr500** [vurtun/nuklear#533]
Sometimes I get this behavior on windows when the content 

![image](https://user-images.githubusercontent.com/1721040/31303846-84e45e24-aada-11e7-81e8-210c6bbe76a9.png)

![image](https://user-images.githubusercontent.com/1721040/31303842-7a67189c-aada-11e7-8add-4308e1e583a6.png)

![image](https://user-images.githubusercontent.com/1721040/31303847-8ac1b1f2-aada-11e7-8c22-2c715eeec1c6.png)

Any way to prevent the contents from going out of bounds?

**Comment by vurtun** [comment]
Hm,
what backend are you using? This looks like a clipping bug similar to #422, maybe even worse since it looks like no clipping is applied at all. So far I was not able reproduce the issue under OpenGL (SDL, GLFW) or X11. Best case scenario would be if you could provide me with a minimal example I could copy & paste into one of the demo backends and debug.

**Comment by fr500** [comment]
I based my code on one of the GLFW samples (back when it was zahnrad) maybe that's the reason. We have our own OpenGL context creation so it's not something easy to test I guess. I'll look at the newer GLFW samples and try to fixit myself before bugging you again :)

**Comment by fr500** [comment]
```
   glDisable(GL_CULL_FACE);
   glDisable(GL_DEPTH_TEST);
   glEnable(GL_SCISSOR_TEST);
   glActiveTexture(GL_TEXTURE0);
```

Derp, fixed
