### ISSUE TITLE
Implemention with nanovg 

### ISSUE THREAD

**Issue by stillwarter** [vurtun/nuklear#539]
Hi ALL:
I found out nuklear's older version has implemention with nanovg, but it was removed.
Just want to know why.
thanks for your reply!

**Comment by lieff** [comment]
I do not know for sure, but may be because it do not needed? Nanovg triangulates shapes, but nuklear provides already triangulated primitives. Only thing can be used it's built in nanovg AA, but its works only in limited cases, in some cases it's buggy and fsaa/msaa etc must be used.

**Comment by stillwarter** [comment]
@lieff hi. I have some questions about these things. Is Nanovg's performance good enough for used in game dev? I don't know which one is better for the implemention of nuklear(opengl or Nanovg). I need both quality and performance. 
Nanovg looks good.
And another question, how to adjust pixel ratio in nuklear?
thanks for your reply

**Comment by lieff** [comment]
Nanovg uses opengl, and in general uses more heavy shader https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L551 than sample nuklear ogl backends (note that nuklear itself do not handle drawing).
Nuklear do not care about pixel ratio, it just gives you triangles coordinates, drawing backend should care to provide nuclear with correct window sizes. Opengl framebuffer size can differ from window size, you must do something like this:  glViewport(0, 0, framebuffer_width, framebuffer_height); and recalculate coordinates from window to framebuffer.

**Comment by vurtun** [comment]
Hey @stillwarter, @lieff 
> I found out nuklear's older version has implemention with nanovg, but it was removed.
Just want to know why.

Nuklear or at that time Zahnrad went through a lot of changes in the first year of development. The reason why I dropped it was just to many changes happening in that time and I needed to reduce complexity so that I don't have to update all backends every time I committed some changes. 

> Is Nanovg's performance good enough for used in game dev

As for performance. At least at that time nanovg was slower. But nanovg is also way more advanced that my own implementations.

When push comes to shove just try it out. Set it up and just throw as much on the screen as possible and look at the numbers. My word is as good as yours, only hard fact count.
