### ISSUE TITLE
Can't change hue in the color picker if the current color is white, gray or black

### ISSUE THREAD

**Issue by megagrump** [vurtun/nuklear#544]
If the selected color is any shade of gray, i. e. all three RGB channels have the same value, the color picker widget requires you to first change the saturation in the main area of the picker before it allows to change hue in the vertical ribbon to the right. Clicking the hue picker does nothing if the selected color is white, black or any shade of gray inbetween.

Example: if the initial color is #FFFFFF, and you want to change it to blue, you first have to select a shade of red before you can select blue.

I discovered this issue in love-nuklear.

**Comment by Heep042** [comment]
This needs another byte that determines hue inside nk_color struct, or anywhere that can store the hue value.

**Comment by vurtun** [comment]
Thanks looks like I will have to introduce a breaking change to the color picker API and use `nk_colorf`. Not really happy about it but yeah. Adding another bye inside color would be even worse.

**Comment by Heep042** [comment]
To be fair, now thinking the hue problem would still persist if the color was pitch black. Here is a non-breaking solution. How about an ability to pass a pointer for the hue value to a color picker, which would be checked against if the color was black? Of course, this could be done in such a way that the original API would not be broken by renaming the original function, wrapping it by a wrapper which passes a null pointer, then, if the passed pointer is not null, check if the passed color RGB values are equal to a color created from the passed color's s and v values and the hue pointer value. If so, then we use the hue pointer's value for the hue slider, and otherwise, adjust the hue pointer as well.

**Comment by vurtun** [comment]
While alluring I think a breaking change is a better fit. I prefer not to introduce to many hacks that will spiral out of control in the future. Had to many bad experiences in the past.

**Comment by AregevDev** [comment]
Hi, this still occurs for me, what should I do?

**Comment by dumblob** [comment]
@AregevDev how do you use Nuklear (source snippet) and which [backend](https://github.com/vurtun/nuklear/tree/master/demo )? Do you have the latest version?

**Comment by AregevDev** [comment]
Under second inspection, the issue is only when changing the color to black, as said above:
I am using GLFW and OpenGL3
```cpp
if (nk_begin(nkContext, "Debug", nk_rect(10, 10, 180, 300),
                     NK_WINDOW_MOVABLE | NK_WINDOW_TITLE | NK_WINDOW_SCALABLE | NK_WINDOW_SCALABLE |
                     NK_WINDOW_MINIMIZABLE)) {
            nk_layout_row_dynamic(nkContext, 20, 1);
            nk_property_float(nkContext, "mix", 0.0f, &mix, 1.0f, 0.1f, 0.01f);
            nk_property_float(nkContext, "fov", 0.25f, &fov, 110.0f, 1.0f, 1.0f);
            nk_label(nkContext, "background", NK_TEXT_LEFT);
            nk_layout_row_dynamic(nkContext, 120, 1);
            bgColor = nk_color_picker(nkContext, bgColor, NK_RGBA);
        }
        nk_end(nkContext);
```
Snip

**Comment by dumblob** [comment]
Good. Are you using the **latest version** of `nuklear.h` and the corresponding backend?

**Comment by AregevDev** [comment]
I used it from master branch, just downloaded the repo
