### ISSUE TITLE
Do you plan to add cascading menus and dock panel?

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#547]
Because many programs now require cascading menus and dock panels,  and hope add these functions

**Comment by RobertoMalatesta** [comment]
I'd like cascading menus (and tables) in Nuklear UI as well, @zhouxs1023 .
That would allow me to drop half a dozen of JS frameworks I currently follow. :P
But, unfortunately, it seems that cascading menus are not in the favor and the scope of the projects, for technical difficulties as well, see:
#346

-- Rob

**Comment by vurtun** [comment]
Like @RobertoMalatesta said. There are good technical as well as personal reasons why I don't have cascading menus. Under normal circumstances there shouldn't be anything that requires cascading menus at all. But since this is a replicate of #346 that was even opened by you @zhouxs1023  I will close this issue.
