### ISSUE TITLE
Unreadable fonts

### ISSUE THREAD

**Issue by steve4444** [vurtun/nuklear#633]
With MSYS2 I used:

    pacman -Syu base-devel mingw-w64-x86_64-gcc git
    pacman -Syu mingw64/mingw-w64-x86_64-glew mingw64/mingw-w64-x86_64-glfw mingw64/mingw-w64-x86_64-freeglut 
    git clone https://github.com/vurtun/nuklear.git
    cd nuklear/demo/glfw_opengl3
    make
    ./bin/demo

The app works but fonts are unreadable.

1. How can I control font size?
2. Can I make the font adapt to screen resolution?
3. How can I avoid the Windows command console to show?

**Comment by fr500** [comment]
for 3, add -mwindows to ldflags

**Comment by vurtun** [comment]
> 1. How can I control font size?

I presume you are using the `glfw_open3` so font loading looks like this: 
```c
struct nk_font_atlas *atlas;
nk_glfw3_font_stash_begin(&atlas);
nk_glfw3_font_stash_end();
```
To load the default font with a specific height do:
```c
struct nk_font *default_font;
struct nk_font_atlas *atlas;
nk_glfw3_font_stash_begin(&atlas);
default_font = nk_font_atlas_add_default(atlas, YOUR_FONT_HEIGHT, 0);
nk_glfw3_font_stash_end();
nk_style_set_font(ctx, &default_font->handle);
```
> Can I make the font adapt to screen resolution?

I don't think there is a automatic way of doing that (you can try `-mwindows` like @fr500 adviced). But yourself can manually calculate the font height from screen resolution.

> 3. How can I avoid the Windows command console to show

Sorry I don't use `mingw` I only now the solution for Visual Studio which requires the application to be compiled as a `Window` application instead of `Console` application.
