### ISSUE TITLE
What are the OS requirements for this GUI?

### ISSUE THREAD

**Issue by jkleiser** [vurtun/nuklear#64]

**Comment by mscdex** [comment]
That was the first thing I was looking for as well....

**Comment by vurtun** [comment]
OK this will be a little bit more lengthy to explain. First of the library works from hardware like consoles  to PCs without any dependencies. This can be taken as far as not having any kind of window at all and drawing everything into a buffer. The approach I take is quite simple. I do not dictate the source of user input at all it can even just come from code itself. Furthermore I do not render anything to screen myself instead I only buffer draw calls that need to be executed. The draw calls buffer is an intermediate format and can be converted into vertexes or directly drawn by platform or hardware specific driver/libraries. So there are no direct requirements for the OS outside basic resources like memory and performance.


Since I don't know how far you want me to go I will describe some basic requirements for memory and performance as well for this library.
At the base minimum the library requires memory for the context (~15k), windows with ~1k per window, panels which takes ~280 bytes and finally the draw commands as well. So far I was able to fit all combined examples in under 64k memory so the memory consumption is quite low. If that is even to much there are ways to scale down the memory requirements even more.


Performance is a little bit more complex. The normal version is frame based with loop based updates which takes some performance (not that bad for modern hardware, for example even X11 has no performance problems). If that is not feasible either because of performance or energy consumption the loop can be modified to only run on application updates and user input. Still the hardware has to be able to redraw the complete screen since this library does not support partial draw updates like GUIs from the 80th and the early 90th.

Hopefully this explains the question and I did not misunderstand the question if so fell free to ask again.

**Comment by jkleiser** [comment]
Thank you for your detailed explanation. As I understand it, this may not be the first GUI library to consider if one wanted to make a game or some other simple application on Mac or Linux, using a language like Lua or Pony. Correct me if I'm wrong. ;-)

**Comment by vurtun** [comment]
At the moment I don't have bindings to Lua or any other language so it would require some work to create it. I just released the library so there is was no time either for me or somebody else to write bindings. 

> As I understand it, this may not be the first GUI library to consider if one wanted to make a game or some other simple application on Mac or Linux, using a language like Lua or Pony.

What I described above is the minimum requirements (I answered mainly for embedded developer since I did not know where the question is heading). But Nuklear can also be used with vertex buffer output, font handling and even default font (only requires a few defines to be set). With that and default configuration it is quite easy to just plug in the library and use one of the platform demos and everything will just work (suited for small apps). If more control is required for example for games it is possible to take away some control away from the library and manage memory, configure style, use skinning or even provide your own font implementation.

**Comment by gozes** [comment]
So I am little confuse, If I, or anyone, where to write bindings for it in language x to be use for PC apps then what would the buildings need to provide, aside from the bindings it self, to make it work on let say *nix

**Comment by vurtun** [comment]
Do you mean what function or parts of the library would need bindings for other languages?

If so this answer depends on how far you want to go. In your case with language bindings for an app you are writing and just want to target one platform it would be best to only bind the actual UI API (at the top of `nuklear.h`) and provide the platform dependent code (input, rendering, font) in C. If you want a little bit more control one possible solution would be to just bind one of the demo platform abstractions (found inside nk_nuklear_xxx.h) for the platform depended part. The are a lot of possibilities and it depends on what you need.
