### ISSUE TITLE
Discussion: whether stb_texedit, stb_truetype and stb_rectpack can be used as a separate file

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#642]
1. Can reduce the size of the Nuklear.h file;
2. Can upgrade stb_texedit, stb_truetype and stb_rectpack header file easily(similar to imgui);
3. Along with the increase of the size of the file, it can be easily opened;
4. Can read all the header files easily;

**Comment by vurtun** [comment]
Hey @zhouxs1023,
this is a complicated topic for me. Shortly before the release of nuklear all stb libraries where separate and this library was made out of a single header and source file. On release I copied everything together. 

There were some reasons for that. The reason why I packet the stb libraries together with nuklear was that often times projects already use one or multiple of these. The problem arises on different versions used. Now suddenly you have multiple copies of the same library and possibly conflicts. Not great. So what I did is rename everything and gave every identifier the `nk_` prefix to make sure that there are no clashes with already included stb libraries.

Another reason why I packet all stb_libraries were warnings generated. At least with GCC and Clang each header generated a lot of warnings. So I fixed most of them in my version.

The reason why this library is single header instead of source + header was the ability to configure nuklear without any kind of build system interaction. Just define what you want and include the single file into your source. I also only use single compilation unit builds so I only had to include nuklear once.

OK so far I only talked about my past reasoning and decision why nuklear is single header and packs all stb libraries together.  If I had to make the same decision again I would do it differently. 

First of all I would make it header plus source file. Single header is not a problem if the header portions is relatively small but the header in nuklear is already bigger than some single header libraries which is just crazy.

 I also would separate out all stb libraries as well as the font altas and the SVG-rasterizer.  They have nothing to do with the core functionality and could be optionally included if needed. The benefit would be that each of these optional components could be viewed, updated and used separately. Honestly some components like the font atlas just have some awefull code in it and could benefit from a good rewrite, but it is to messy at the moment.

Additional advantage could be that if all these components are both optional and separate, it would be a lot more obvious that it is easy to use other libraries like NanoVG to do the rendering and font handling. 

So to bring this small rant to an end. What I just said is all fine and good but the problem is nuklear is used by other people so I just cannot change everything as I feel. There is code out there using nuklear expecting it to be as it is now. 

If there is a general demand of enough people to separate out each component I personally have nothing against it. But these are very heavy changes. Not so much in code itself but file layout. So I am interested to see what people want.

**Comment by dumblob** [comment]
This is the reason why e.g. SQLite is developed in separate files (components) and then there is the amalgamation process which puts it all together to a single file. Not sure though whether it makes sense for Nuklear as there is this another [baby of yours](https://gist.github.com/vurtun/c5b0374c27d2f5e9905bfbe7431d9dc0 ) :wink:.

**Comment by vurtun** [comment]
> This is the reason why e.g. SQLite is developed in separate files (components) and then there is the amalgamation process which puts it all together to a single file.

Possibility. Shouldn't even be to hard to write. Also could include a feature to remove all documentation comments and other features. I think that would be the best solution. As soon as I have a little bit more time I will write up a test version and see if I can get it to work. Hopefully separated files would make it easier for outsider to modify the implementation more to their needs.

 >  Not sure though whether it makes sense for Nuklear as there is this another baby of yours

The new version still needs a lot of work and time. So far still missing a lot of features to even become on feature par with nuklear and is also missing a few core details.  But in general would agree. I don't want to rewrite nuklear but I think I could reuse parts of it like the font atlas and draw list which ties back into separating out parts of nuklear.
