### ISSUE TITLE
nuklear vs dear imgui UX

### ISSUE THREAD

**Issue by dkrikun** [vurtun/nuklear#693]
Hello,

I've been using [ocornut/imgui](https://github.com/ocornut/imgui) for a few years now, and it serves me well, but its API is kinda complicated and its C++, so I found nuklear to be a much cleaner imgui library, in terms of API, language and design.

But, and it is a big but for me, the dear imgui UX out-of-the-box is significantly better. It looks better and it's easy to use. The font is better, the layout is better too.

Are there any ongoing efforts to improve this area?
Related: does it seem feasible to combine both libraries somehow, to get both benefits?

**Comment by vurtun** [comment]
I laughed out loud the first time I read your issue. Harsh critique. But the problem with critics is they talk a lot and don't do. 

Yes both dear imgui and nuklear have problems and different core values or even reason to exist in the first place. However the only magical case the best of each is combined would be if both omar and I would work together and were actually able to combine the pros while avoiding all the cons. 

That won't happen simply because I don't have the time anymore to work extensively on open source. At some point we all have to start paying bills and open source does not.

As for a possible solution to your problem you might me interested in [cimgui](https://github.com/Extrawurst/cimgui). It is a C conversion from dear imgui.

**Comment by dkrikun** [comment]
Sorry for being bold. I hold huge respect for both tools.

As for cimgui, it only solves the language problem, and it's definitely a
second class citizen.

What I'm suggesting is to mix nuklear design and api with dear imgui ux.
What do you think, it's feasible or nonsense?

**Comment by vurtun** [comment]
You can still write your own version and this is not a joke suggestion. If you simplify enough and maybe take code from dear imgui and nuklear like drawing and font it shouldn't even take to much time and effort. The very first minimal version of nuklear only took me a few days/week. Probably the biggest advantage of immediate mode GUIs is that it is relatively easy to write your own simple version.
