### ISSUE TITLE
Issues with High DPI displays

### ISSUE THREAD

**Issue by Leandros** [vurtun/nuklear#74]
The example doesn't seem to work well on High DPI displays (like on my 5k display).
Additionally to being tiny, the mouse isn't correctly detected (as you see on the hover state in the image below).
IIRC, SDL has flags, you can set while creating the window which enables high dpi support.
GLFW requires a little more work, quoting there changelog from a few years back:

> GLFW now supports high-DPI monitors on both Windows and OS X, giving windows full resolution framebuffers where other UI elements are scaled up. To achieve this, glfwGetFramebufferSize and glfwSetFramebufferSizeCallback have been added. These work with pixels, while the rest of the GLFW API works with screen coordinates. This is important as OpenGL uses pixels, not screen coordinates.

<img width="1312" alt="screen shot 2016-04-19 at 15 29 43" src="https://cloud.githubusercontent.com/assets/396475/14640837/b4a5c1c6-0643-11e6-8437-53b33873e380.png">

**Comment by Leandros** [comment]
Changing any calls to `glfwGetWindowSize` to `glfwGetFramebufferSize` will fix the rendering, but not control, since the mouse coordinates of glfw are in screen coordinates, not in pixels (as expected by nuklear).
Each the x and y coordinates would have to be adjusted for the size, by, for example, multiplying with the factor.

Attached is a patch for a fix of the node_editor (based on this branch https://github.com/fdb/nuklear/tree/osx-support)
[node_editor_fix.patch.txt](https://github.com/vurtun/nuklear/files/226003/node_editor_fix.patch.txt)

**Comment by dumblob** [comment]
Ok, the patch seems to solve the technical issues, but the "High DPI" issue remains. In reality, it's not an issue, but rather a feature of Nuklear. It has been already discussed some time ago in https://github.com/vurtun/nuklear/issues/10 .

And the current state of being does make very much sense, because exactly for such purposes [Cassowary algorithm](http://constraints.cs.washington.edu/cassowary/ ) (as mentioned in https://github.com/vurtun/nuklear/issues/10#issuecomment-129195813 ) etc. was invented. Read more about it on https://github.com/ocornut/imgui/issues/268 and about a possible solution in https://github.com/ocornut/imgui/issues/268#issuecomment-129226867 .

**Comment by vurtun** [comment]
@Leandros Thanks for your issue and patch. Could you create a PR? This would make it easier for me to see what needs to be done and how it works.

**Comment by spworley** [comment]
Unfortunately the updated code seems to have flipped the correction terms.
 
The lines like:
 x *= (double)(int)((float)width/(float)display_width);
 y *= (double)(int)((float)height/(float)display_height);

should really just be  
 x *= display_width/(float)width;
 y *= display_height/(float)height;

This fixes the mouse mapping, though not the size scaling of the UI itself.

**Comment by vurtun** [comment]
@spworley Can I use for a quick test if what I did to fix it worked out?
