### ISSUE TITLE
usuable for embedded microcontrollers?

### ISSUE THREAD

**Issue by flip111** [vurtun/nuklear#77]
In a project i used to work on we used a proprietary videochip to draw basic user interfaces. Could such a setup be replaced by a microntroller + some ram serving as frame buffer? Code size and memory usage are very important. Of course it depends on the complexity of the GUI. What about a "hello world"-GUI and a more complex GUI though? And a second question: how much would still have to be written with this library as you are running on bare metal in this case.

**Comment by vurtun** [comment]
I wrote a little bit about that in issue #64 but I will just copy paste it here:
> OK this will be a little bit more lengthy to explain. First of the library works from hardware like consoles to PCs without any dependencies. This can be taken as far as not having any kind of window at all and drawing everything into a buffer. The approach I take is quite simple. I do not dictate the source of user input at all it can even just come from code itself. Furthermore I do not render anything to screen myself instead I only buffer draw calls that need to be executed. The draw calls buffer is an intermediate format and can be converted into vertexes or directly drawn by platform or hardware specific driver/libraries. So there are no direct requirements for the OS outside basic resources like memory and performance.
Since I don't know how far you want me to go I will describe some basic requirements for memory and performance as well for this library.
At the base minimum the library requires memory for the context (~15k), windows with ~1k per window, panels which takes ~280 bytes and finally the draw commands as well. So far I was able to fit all combined examples in under 64k memory so the memory consumption is quite low. If that is even to much there are ways to scale down the memory requirements even more.
Performance is a little bit more complex. The normal version is frame based with loop based updates which takes some performance (not that bad for modern hardware, for example even X11 has no performance problems). If that is not feasible either because of performance or energy consumption the loop can be modified to only run on application updates and user input. Still the hardware has to be able to redraw the complete screen since this library does not support partial draw updates like GUIs from the 80th and the early 90th.
Hopefully this explains the question and I did not misunderstand so fell free to ask again.

**Comment by flip111** [comment]
Nice answer, which already tells a lot. Some things i don't understand, this in particular

> Still the hardware has to be able to redraw the complete screen since this library does not support partial draw updates like GUIs from the 80th and the early 90th.

I'm not familiar with GUI's and partial updates from the 80th and the early 90th. Maybe you have a good reference on this or can explain in a few sentences what the actual requirement on the underlying hardware system is?

> I only buffer draw calls that need to be executed

How is the draw call specified?

> the loop can be modified to only run on application updates and user input.

Is this trivial to make or is this going to complicate much?

> Code size and memory usage are very important

What is the code size for the library + "hello world"-gui?

**Comment by vurtun** [comment]
> I'm not familiar with GUI's and partial updates from the 80th and the early 90th. Maybe you have a good reference on this or can explain in a few sentences what the actual requirement on the underlying hardware system is?

This is quite easy at that time computer were not able to redraw the complete screen for performance reasons. So all GUI libraries would only draw portions of the screen that haven't been updated. This is quite some time ago and not an issue today (even with microcontroller!).

> How is the draw call specified?

A draw call is just a simple shape for example `nk_command_rect_filled`:

```c
struct nk_command_rect_filled {
    struct nk_command header;
    unsigned short rounding;
    short x, y;
    unsigned short w, h;
    struct nk_color color;
};
```
These are buffered and at the end of the frame either drawn by calling your own drawing function or you can convert all draw commands (shapes) into a hardware accessible (vertex + elements buffer for graphics cards)

> Is this trivial to make or is this going to complicate much?

There is already code for iOS that tested it. I even had an issue sometime ago #39 where we went through it to get it done. But I can help out to make it work it is not to complicated.

> What is the code size for the library + "hello world"-gui?
I had code that measure the memory consumption but because of the release I did not add it in again. The base cost for the example on the front page is ~15k for context (like I said can be reduced), ~1k for window state and for commands I am not quite sure but I remember that combined window + commands did not exceed 4k (if wanted I can write a small test case to provide more information but could take some time I am currently quite overwhelmed with issues and PRs).

**Comment by flip111** [comment]
By "memory consumption" i would understand the memory that is being allocated by the program during runtime. However the program itself also needs to be stored somewhere (the binary). This program memory is also limited on embedded systems. Now i'm confused which of the two you are specifying ... In any case i would like to know both. For target platform you can think of ARM Cortex-M4 weaker MCU's like Cortex-M3 or even Cortex-M0 would be nice, but i don't think those systems are feasible because you indicated that the library needs "under 64K memory" which i take as 64K memory to be on the safe side, and the M3 and M0 MCU's usually don't come with 64K of memory (both code memory as well as RAM).

**Comment by vurtun** [comment]
So far I only talked about allocated memory. Binary can be made smaller as well for example by not compiling modules that are not needed (font baking, draw list and the default font). I cannot tell you any fixed numbers so it is probably best to test things out.

How much memory you need to allocate depends on how much stuff can be displayed on screen, everything else is clipped and does not need memory. So smaller windows/screens need less memory. As for fitting everything into 64k I cannot make any promises and would require testing and maybe tweaking the library.
