### ISSUE TITLE
The cppcheck generates a lot of warnings about nullptr dereferencing

### ISSUE THREAD

**Issue by codemeow** [vurtun/nuklear#90]
Hello!

I have used the following command to check the code:

`alex@alex-VirtualBox:~/Проекты/test/vurtun$ /opt/cppcheck/cppcheck-1.72/cppcheck -q -j4     --enable=performance,portability,warning,style     /home/alex/Проекты/test/vurtun/
`

And it shown a lot of places where the nullptr dereferencing takes place.
Ex.:
`[/home/alex/Проекты/test/vurtun/nuklear/nuklear.h:14824] -> [/home/alex/Проекты/test/vurtun/nuklear/nuklear.h:14825]: (warning) Either the condition '!ctx' is redundant or there is possible null pointer dereference: ctx.`

Also there are meaningless conditions and memory issues:
`[/home/alex/Проекты/test/vurtun/nuklear/nuklear.h:7774]: (style) Redundant condition: If 'EXPR < 0', the comparison '!(EXPR > 0)' is always true.
`
`[/home/alex/Проекты/test/vurtun/nuklear/example/file_browser.c:235]: (error) Common realloc mistake: 'results' nulled but not freed upon failure`

The full log is here: http://pastebin.com/c5LVJ1MK
Errors subset is here: http://pastebin.com/DxRnwz0V
Warnings subset is here: http://pastebin.com/Q8eRUqzg
Style subset is here: http://pastebin.com/9DbJjf8U

**Comment by vurtun** [comment]
Thanks for providing this in a readable way! Many just would have dumped it on me.

> And it shown a lot of places where the nullptr dereferencing takes place.

Yeah the same for coverity. The reason for this is quite simple. I use a custom define for assert so users can overwrite and use their own assert macro. The problem is most static analyzer fail to notice it and alert pointer dereferences and redundant code.

> Also there are meaningless conditions and memory issues

The condition was a correct find (side note it even looks like this caused the font bug) and I fixed it just like the memory allocation issue. Other than that I fixed the unused `active` variable. The rest seems to be smaller scope issues.

Once again thanks for your work!
